// AUTO-GENERATED by `cargo run -p elevator-layout-codegen`. DO NOT EDIT.
//
// Source-of-truth: #[repr(C)] + #[derive(MultiHostLayout)] in
// crates/elevator-ffi/src/lib.rs.

using System.Runtime.InteropServices;

namespace ElevatorHarness;

internal static partial class Native {

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct EvAssignment {
        [FieldOffset(0)] public ulong line_entity_id;
        [FieldOffset(8)] public ulong car_entity_id;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct EvCarCall {
        [FieldOffset(0)] public ulong car_entity_id;
        [FieldOffset(8)] public ulong floor_entity_id;
        [FieldOffset(16)] public ulong press_tick;
        [FieldOffset(24)] public ulong acknowledged_at;
        [FieldOffset(32)] public uint ack_latency_ticks;
        [FieldOffset(36)] public uint pending_rider_count;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct EvElevatorParams {
        [FieldOffset(0)] public double max_speed;
        [FieldOffset(8)] public double acceleration;
        [FieldOffset(16)] public double deceleration;
        [FieldOffset(24)] public double weight_capacity;
        [FieldOffset(32)] public uint door_transition_ticks;
        [FieldOffset(36)] public uint door_open_ticks;
        [FieldOffset(40)] public double inspection_speed_factor;
        [FieldOffset(48)] public double bypass_load_up_pct;
        [FieldOffset(56)] public double bypass_load_down_pct;
    }

    [StructLayout(LayoutKind.Explicit, Size = 88)]
    public struct EvElevatorView {
        [FieldOffset(0)] public ulong entity_id;
        [FieldOffset(8)] public uint group_id;
        [FieldOffset(16)] public ulong line_id;
        [FieldOffset(24)] public byte phase;
        [FieldOffset(32)] public double position;
        [FieldOffset(40)] public double velocity;
        [FieldOffset(48)] public ulong current_stop_id;
        [FieldOffset(56)] public ulong target_stop_id;
        [FieldOffset(64)] public uint occupancy;
        [FieldOffset(72)] public double capacity_kg;
        [FieldOffset(80)] public byte door_state;
        [FieldOffset(81)] public byte going_up;
        [FieldOffset(82)] public byte going_down;
    }

    [StructLayout(LayoutKind.Explicit, Size = 88)]
    public struct EvEvent {
        [FieldOffset(0)] public byte kind;
        [FieldOffset(1)] public sbyte direction;
        [FieldOffset(2)] public byte code1;
        [FieldOffset(3)] public byte code2;
        [FieldOffset(4)] public uint group;
        [FieldOffset(8)] public ulong tick;
        [FieldOffset(16)] public ulong stop;
        [FieldOffset(24)] public ulong car;
        [FieldOffset(32)] public ulong rider;
        [FieldOffset(40)] public ulong floor;
        [FieldOffset(48)] public ulong entity;
        [FieldOffset(56)] public ulong count;
        [FieldOffset(64)] public double f1;
        [FieldOffset(72)] public double f2;
        [FieldOffset(80)] public ulong tag;
    }

    [StructLayout(LayoutKind.Explicit, Size = 88)]
    public struct EvFrame {
        [FieldOffset(0)] public System.IntPtr elevators;
        [FieldOffset(8)] public System.UIntPtr elevator_count;
        [FieldOffset(16)] public System.IntPtr stops;
        [FieldOffset(24)] public System.UIntPtr stop_count;
        [FieldOffset(32)] public System.IntPtr riders;
        [FieldOffset(40)] public System.UIntPtr rider_count;
        [FieldOffset(48)] public EvMetricsView metrics;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct EvHallCall {
        [FieldOffset(0)] public ulong stop_entity_id;
        [FieldOffset(8)] public sbyte direction;
        [FieldOffset(16)] public ulong press_tick;
        [FieldOffset(24)] public ulong acknowledged_at;
        [FieldOffset(32)] public ulong assigned_car;
        [FieldOffset(40)] public ulong destination_entity_id;
        [FieldOffset(48)] public byte pinned;
        [FieldOffset(52)] public uint pending_rider_count;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct EvLogMessage {
        [FieldOffset(0)] public byte level;
        [FieldOffset(8)] public long ts_ns;
        [FieldOffset(16)] public System.IntPtr msg_ptr;
        [FieldOffset(24)] public uint msg_len;
    }

    [StructLayout(LayoutKind.Explicit, Size = 112)]
    public struct EvMetrics {
        [FieldOffset(0)] public ulong total_delivered;
        [FieldOffset(8)] public ulong total_abandoned;
        [FieldOffset(16)] public ulong total_spawned;
        [FieldOffset(24)] public ulong total_settled;
        [FieldOffset(32)] public ulong total_rerouted;
        [FieldOffset(40)] public ulong throughput;
        [FieldOffset(48)] public double avg_wait_ticks;
        [FieldOffset(56)] public ulong max_wait_ticks;
        [FieldOffset(64)] public double avg_ride_ticks;
        [FieldOffset(72)] public double avg_utilization;
        [FieldOffset(80)] public double abandonment_rate;
        [FieldOffset(88)] public double total_distance;
        [FieldOffset(96)] public ulong total_moves;
        [FieldOffset(104)] public double reposition_distance;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct EvMetricsView {
        [FieldOffset(0)] public ulong total_delivered;
        [FieldOffset(8)] public ulong total_abandoned;
        [FieldOffset(16)] public double avg_wait_seconds;
        [FieldOffset(24)] public double avg_ride_seconds;
        [FieldOffset(32)] public ulong current_tick;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct EvRiderView {
        [FieldOffset(0)] public ulong entity_id;
        [FieldOffset(8)] public byte phase;
        [FieldOffset(16)] public ulong origin_stop_id;
        [FieldOffset(24)] public ulong destination_stop_id;
        [FieldOffset(32)] public ulong elevator_id;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct EvStopView {
        [FieldOffset(0)] public ulong entity_id;
        [FieldOffset(8)] public uint stop_id;
        [FieldOffset(16)] public double position;
        [FieldOffset(24)] public uint waiting;
        [FieldOffset(28)] public uint residents;
        [FieldOffset(32)] public uint abandoned;
        [FieldOffset(40)] public System.IntPtr name_ptr;
        [FieldOffset(48)] public System.UIntPtr name_len;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct EvTaggedMetric {
        [FieldOffset(0)] public double avg_wait_ticks;
        [FieldOffset(8)] public ulong max_wait_ticks;
        [FieldOffset(16)] public ulong total_delivered;
        [FieldOffset(24)] public ulong total_abandoned;
        [FieldOffset(32)] public ulong total_spawned;
    }
}
