//! Consumer-side layout codegen for elevator-ffi.
//!
//! Iterates the `elevator-layout-runtime::REGISTRY` distributed slice
//! (populated at link time by every `#[derive(MultiHostLayout)]` in
//! elevator-ffi) and emits three host-side files from a single Rust
//! source-of-truth:
//!
//!   - `examples/csharp-harness/Generated.cs` — C# struct definitions
//!     with `[StructLayout(LayoutKind.Explicit)]` + `[FieldOffset(N)]`
//!     per field. Added to the .csproj as a Compile target.
//!   - `examples/gms2-extension/extension/elevator_ffi/elevator_ffi_layout.gml`
//!     — GML `#macro EV_<STRUCT>_<FIELD>_OFFSET N` constants for the
//!     buffer_peek decoders.
//!   - `examples/gms2-harness/layout_asserts.h` — C `_Static_assert`
//!     lines pinning every offset, so a future cbindgen reorder fails
//!     CI in ffi-harness before the GML decoders break.
//!
//! Output is sorted by struct name + declaration order so re-runs
//! produce byte-identical files. CI's `layout-drift-gate` step
//! verifies the committed files match `cargo run -p
//! elevator-layout-codegen` output.

// `linkme` distributed slices only collect entries from crates
// whose symbols are live-linked into the binary's call graph. This
// `use` keeps elevator-ffi's metadata pulled in even though we
// don't directly call any of its functions — without it the linker
// dead-code-eliminates every #[derive(MultiHostLayout)] entry and
// REGISTRY ends up empty at runtime.
use elevator_ffi as _;
use elevator_layout_runtime::{Field, FieldKind, LayoutEntry, REGISTRY};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> std::io::Result<()> {
    let repo_root = repo_root();
    let mut entries: Vec<&LayoutEntry> = REGISTRY.iter().collect();
    // Stable order: struct names alphabetically. Field declaration
    // order is preserved by the proc-macro's slice emission.
    entries.sort_by_key(|e| e.name);

    let csharp = render_csharp(&entries);
    let gml = render_gml(&entries);
    let c_asserts = render_c_asserts(&entries);

    write_if_changed(
        &repo_root.join("examples/csharp-harness/Generated.cs"),
        &csharp,
    )?;
    write_if_changed(
        &repo_root.join("examples/gms2-extension/extension/elevator_ffi/elevator_ffi_layout.gml"),
        &gml,
    )?;
    write_if_changed(
        &repo_root.join("examples/gms2-harness/layout_asserts.h"),
        &c_asserts,
    )?;

    eprintln!("wrote {} struct definitions to 3 host files", entries.len());
    Ok(())
}

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at the codegen crate; back up two
    // levels to the workspace root.
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| manifest.to_path_buf())
}

fn write_if_changed(path: &Path, content: &str) -> std::io::Result<()> {
    let existing = fs::read_to_string(path).ok();
    if existing.as_deref() == Some(content) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

const HEADER_NOTICE: &str =
    "AUTO-GENERATED by `cargo run -p elevator-layout-codegen`. DO NOT EDIT.";

fn render_csharp(entries: &[&LayoutEntry]) -> String {
    // Set of struct names so nested-field lookups can decide
    // "embed the named struct" vs "fall back to IntPtr".
    let known_structs: std::collections::HashSet<&str> = entries.iter().map(|e| e.name).collect();

    let mut out = String::new();
    writeln!(out, "// {HEADER_NOTICE}").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Source-of-truth: #[repr(C)] + #[derive(MultiHostLayout)] in",
    )
    .unwrap();
    writeln!(out, "// crates/elevator-ffi/src/lib.rs.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "using System.Runtime.InteropServices;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "namespace ElevatorHarness;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "internal static partial class Native {{").unwrap();
    for entry in entries {
        writeln!(out).unwrap();
        writeln!(
            out,
            "    [StructLayout(LayoutKind.Explicit, Size = {})]",
            entry.size
        )
        .unwrap();
        writeln!(out, "    public struct {} {{", entry.name).unwrap();
        for field in entry.fields {
            let cs_type = csharp_field_type(field, &known_structs);
            writeln!(
                out,
                "        [FieldOffset({})] public {} {};",
                field.offset, cs_type, field.name,
            )
            .unwrap();
        }
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "}}").unwrap();
    out
}

fn csharp_field_type(field: &Field, known_structs: &std::collections::HashSet<&str>) -> String {
    // Nested repr-C struct: prefer the typed embed over IntPtr so
    // C# consumers can reach into nested fields (e.g.
    // `frame.metrics.total_delivered` on EvFrame).
    if matches!(field.kind, FieldKind::Bytes) && known_structs.contains(field.type_name) {
        return field.type_name.to_string();
    }
    match field.kind {
        FieldKind::U8 => "byte".to_string(),
        FieldKind::I8 => "sbyte".to_string(),
        FieldKind::U16 => "ushort".to_string(),
        FieldKind::I32 => "int".to_string(),
        FieldKind::U32 => "uint".to_string(),
        FieldKind::U64 => "ulong".to_string(),
        FieldKind::I64 => "long".to_string(),
        FieldKind::F32 => "float".to_string(),
        FieldKind::F64 => "double".to_string(),
        FieldKind::Ptr => "System.IntPtr".to_string(),
        FieldKind::UPtr => "System.UIntPtr".to_string(),
        // Bytes is opaque — keep as IntPtr-sized field; consumers
        // that need real byte content should add a manual decoder.
        FieldKind::Bytes => "System.IntPtr".to_string(),
        // FieldKind is non_exhaustive in the runtime crate; surface
        // an unknown variant explicitly so a future kind addition
        // forces an update here rather than silently picking a
        // wrong C# type.
        _ => "/* unknown FieldKind — codegen needs an update */ System.IntPtr".to_string(),
    }
}

fn render_gml(entries: &[&LayoutEntry]) -> String {
    let mut out = String::new();
    writeln!(out, "// {HEADER_NOTICE}").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Source-of-truth: #[repr(C)] + #[derive(MultiHostLayout)] in",
    )
    .unwrap();
    writeln!(out, "// crates/elevator-ffi/src/lib.rs.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Use these macros with `buffer_peek` to decode FFI buffers:"
    )
    .unwrap();
    writeln!(
        out,
        "//   var _level = buffer_peek(_buf, EV_LOG_MESSAGE_LEVEL_OFFSET, buffer_u8);",
    )
    .unwrap();
    for entry in entries {
        let snake = pascal_to_snake_upper(entry.name);
        writeln!(out).unwrap();
        writeln!(out, "// ── {} ({} bytes) ──", entry.name, entry.size).unwrap();
        writeln!(out, "#macro {}_SIZE {}", snake, entry.size).unwrap();
        for field in entry.fields {
            let field_upper = field.name.to_ascii_uppercase();
            writeln!(
                out,
                "#macro {}_{}_OFFSET {}",
                snake, field_upper, field.offset
            )
            .unwrap();
        }
    }
    out
}

fn pascal_to_snake_upper(s: &str) -> String {
    // "EvLogMessage" → "EV_LOG_MESSAGE". Two-character acronym
    // detection isn't needed — every host-bound struct in our
    // surface starts with single-character "Ev" prefix only.
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.char_indices() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

fn render_c_asserts(entries: &[&LayoutEntry]) -> String {
    let mut out = String::new();
    writeln!(out, "/* {HEADER_NOTICE} */").unwrap();
    writeln!(out, "/*").unwrap();
    writeln!(
        out,
        " * Source-of-truth: #[repr(C)] + #[derive(MultiHostLayout)] in"
    )
    .unwrap();
    writeln!(out, " * crates/elevator-ffi/src/lib.rs.").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(
        out,
        " * Compile-time asserts pinning every field offset and total"
    )
    .unwrap();
    writeln!(
        out,
        " * struct size. A future cbindgen reorder breaks ffi-harness"
    )
    .unwrap();
    writeln!(out, " * here, before the GML decoders or C# bindings see").unwrap();
    writeln!(out, " * garbage values.").unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifndef ELEVATOR_FFI_LAYOUT_ASSERTS_H").unwrap();
    writeln!(out, "#define ELEVATOR_FFI_LAYOUT_ASSERTS_H").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();
    writeln!(out, "#include \"elevator_ffi.h\"").unwrap();
    for entry in entries {
        writeln!(out).unwrap();
        writeln!(out, "/* {} ({} bytes) */", entry.name, entry.size).unwrap();
        writeln!(
            out,
            "_Static_assert(sizeof(struct {}) == {}, \"{} size drift\");",
            entry.name, entry.size, entry.name,
        )
        .unwrap();
        for field in entry.fields {
            writeln!(
                out,
                "_Static_assert(offsetof(struct {}, {}) == {}, \"{}.{} offset drift\");",
                entry.name, field.name, field.offset, entry.name, field.name,
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();
    writeln!(out, "#endif /* ELEVATOR_FFI_LAYOUT_ASSERTS_H */").unwrap();
    out
}
