/* Auto-generated by cbindgen. Do not edit. */

#ifndef ELEVATOR_FFI_H
#define ELEVATOR_FFI_H

#pragma once

/* Generated. Do not modify by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Current ABI version. Bumped for any breaking change to the C layout.
 */
#define EV_ABI_VERSION 1

/**
 * `Event::HallButtonPressed`.
 */
#define HALL_BUTTON_PRESSED 1

/**
 * `Event::HallCallAcknowledged`.
 */
#define HALL_CALL_ACKNOWLEDGED 2

/**
 * `Event::HallCallCleared`.
 */
#define HALL_CALL_CLEARED 3

/**
 * `Event::CarButtonPressed`.
 */
#define CAR_BUTTON_PRESSED 4

/**
 * `Event::RiderSkipped`.
 */
#define RIDER_SKIPPED 5

/**
 * Status code returned by every FFI entrypoint.
 */
typedef enum EvStatus {
    /**
     * Operation succeeded.
     */
    Ok = 0,
    /**
     * A required pointer argument was null.
     */
    NullArg = 1,
    /**
     * A C string argument was not valid UTF-8.
     */
    InvalidUtf8 = 2,
    /**
     * The config file could not be read from disk.
     */
    ConfigLoad = 3,
    /**
     * The config file failed to parse as RON.
     */
    ConfigParse = 4,
    /**
     * [`SimulationBuilder::build`] returned an error.
     */
    BuildFailed = 5,
    /**
     * The requested entity, group, or resource was not found.
     */
    NotFound = 6,
    /**
     * An argument was structurally valid but semantically rejected.
     */
    InvalidArg = 7,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    Panic = 99,
} EvStatus;

/**
 * Built-in dispatch strategy identifier.
 */
typedef enum EvStrategy {
    /**
     * SCAN — sweep end-to-end.
     */
    Scan = 0,
    /**
     * LOOK — reverse at last request.
     */
    Look = 1,
    /**
     * Nearest-car.
     */
    NearestCar = 2,
    /**
     * Estimated time to destination.
     */
    Etd = 3,
} EvStrategy;

/**
 * Opaque simulation handle. Layout is not part of the ABI.
 */
typedef struct EvSim EvSim;

typedef struct Option_EvLogFn Option_EvLogFn;

/**
 * View of a single elevator at the current tick.
 */
typedef struct EvElevatorView {
    /**
     * Elevator entity id (raw slotmap `as_ffi()`).
     */
    uint64_t entity_id;
    /**
     * Group id this elevator belongs to (`u32::MAX` if orphaned).
     */
    uint32_t group_id;
    /**
     * Line (shaft/tether) entity id.
     */
    uint64_t line_id;
    /**
     * [`ElevatorPhase`] tag: 0 `Idle`, 1 `MovingToStop`, 2 `Repositioning`,
     * 3 `DoorOpening`, 4 `Loading`, 5 `DoorClosing`, 6 `Stopped`.
     */
    uint8_t phase;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Instantaneous velocity (+ up, - down).
     */
    double velocity;
    /**
     * Current stop (0 if not at a stop / moving).
     */
    uint64_t current_stop_id;
    /**
     * Target stop (0 if idle).
     */
    uint64_t target_stop_id;
    /**
     * Number of riders on board.
     */
    uint32_t occupancy;
    /**
     * Weight capacity in kg.
     */
    double capacity_kg;
    /**
     * [`DoorState`] tag: 0 `Closed`, 1 `Opening`, 2 `Open`, 3 `Closing`.
     */
    uint8_t door_state;
} EvElevatorView;

/**
 * View of a single stop at the current tick.
 */
typedef struct EvStopView {
    /**
     * Stop entity id.
     */
    uint64_t entity_id;
    /**
     * Config-level stop id (as declared in the RON file).
     */
    uint32_t stop_id;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Number of riders currently waiting at this stop.
     */
    uint32_t waiting;
    /**
     * Number of resident (parked) riders at this stop.
     */
    uint32_t residents;
    /**
     * Number of riders who abandoned waiting at this stop.
     */
    uint32_t abandoned;
    /**
     * UTF-8 name bytes borrowed from the frame's arena.
     */
    const uint8_t *name_ptr;
    /**
     * Length in bytes of the name slice at [`Self::name_ptr`].
     */
    uintptr_t name_len;
} EvStopView;

/**
 * View of a single rider at the current tick.
 */
typedef struct EvRiderView {
    /**
     * Rider entity id.
     */
    uint64_t entity_id;
    /**
     * [`RiderPhase`] tag: 0 `Waiting`, 1 `Boarding`, 2 `Riding`, 3 `Exiting`,
     * 4 `Walking`, 5 `Arrived`, 6 `Abandoned`, 7 `Resident`.
     */
    uint8_t phase;
    /**
     * Origin / current stop entity id (0 if none).
     */
    uint64_t origin_stop_id;
    /**
     * Final destination stop entity id (0 if no route).
     */
    uint64_t destination_stop_id;
    /**
     * Elevator carrying the rider (0 if not aboard).
     */
    uint64_t elevator_id;
} EvRiderView;

/**
 * Aggregate metrics at the current tick.
 */
typedef struct EvMetricsView {
    /**
     * Cumulative riders delivered.
     */
    uint64_t total_delivered;
    /**
     * Cumulative riders who abandoned.
     */
    uint64_t total_abandoned;
    /**
     * Average wait time (seconds).
     */
    double avg_wait_seconds;
    /**
     * Average ride time (seconds).
     */
    double avg_ride_seconds;
    /**
     * Current simulation tick.
     */
    uint64_t current_tick;
} EvMetricsView;

/**
 * Borrowed per-tick snapshot. All slice pointers are valid until the next
 * call to [`ev_sim_frame`] on the same handle.
 */
typedef struct EvFrame {
    /**
     * Pointer to contiguous elevator views.
     */
    const struct EvElevatorView *elevators;
    /**
     * Number of elements at [`Self::elevators`].
     */
    uintptr_t elevator_count;
    /**
     * Pointer to contiguous stop views.
     */
    const struct EvStopView *stops;
    /**
     * Number of elements at [`Self::stops`].
     */
    uintptr_t stop_count;
    /**
     * Pointer to contiguous rider views.
     */
    const struct EvRiderView *riders;
    /**
     * Number of elements at [`Self::riders`].
     */
    uintptr_t rider_count;
    /**
     * Aggregate metrics snapshot.
     */
    struct EvMetricsView metrics;
} EvFrame;

/**
 * C-ABI-flat projection of a `HallCall` for FFI consumers.
 */
typedef struct EvHallCall {
    /**
     * Stop entity id (same encoding as elsewhere in the FFI).
     */
    uint64_t stop_entity_id;
    /**
     * `1` = Up, `-1` = Down.
     */
    int8_t direction;
    /**
     * Tick at which the button was pressed.
     */
    uint64_t press_tick;
    /**
     * Tick at which the call was acknowledged; `u64::MAX` if pending.
     */
    uint64_t acknowledged_at;
    /**
     * Car currently assigned to serve the call; `0` if none.
     */
    uint64_t assigned_car;
    /**
     * Destination stop entity id in DCS (`HallCallMode::Destination`)
     * mode, or `0` when the call has no destination (Classic mode,
     * or no kiosk entry yet). Matches `HallCall::destination`.
     */
    uint64_t destination_entity_id;
    /**
     * `1` when pinned, `0` otherwise.
     */
    uint8_t pinned;
    /**
     * Number of riders aggregated onto this call.
     */
    uint32_t pending_rider_count;
} EvHallCall;

/**
 * C-ABI-flat projection of the five hall-call / car-call / skip
 * events emitted by the simulation.
 *
 * All entity-id fields use `0` to mean "not applicable for this
 * event kind" (real entity ids are never zero under the FFI
 * encoding). The `kind` discriminator picks which fields are
 * meaningful — see [`ev_event_kind`] for the kind constants and the
 * [`ev_sim_drain_events`] docs for the per-kind field map.
 */
typedef struct EvEvent {
    /**
     * Event kind discriminator. Values outside [`ev_event_kind`] are
     * reserved — ignore unknown kinds for forward compatibility.
     */
    uint8_t kind;
    /**
     * Direction for hall-call events: `1` = Up, `-1` = Down, `0` = N/A.
     */
    int8_t direction;
    /**
     * Tick the event was emitted on.
     */
    uint64_t tick;
    /**
     * Stop entity id. Meaningful for all three hall-call kinds and
     * for `RiderSkipped` (as the skip site). `0` for `CarButtonPressed`.
     */
    uint64_t stop;
    /**
     * Car entity id. `HallCallCleared.car`, `CarButtonPressed.car`,
     * `RiderSkipped.elevator`. `0` for kinds that don't carry a car.
     */
    uint64_t car;
    /**
     * Rider entity id. `CarButtonPressed.rider` (may be `0` for
     * synthetic presses), `RiderSkipped.rider`. `0` otherwise.
     */
    uint64_t rider;
    /**
     * Floor entity id for `CarButtonPressed` (the requested stop).
     * `0` for every other kind.
     */
    uint64_t floor;
} EvEvent;

/**
 * Return the ABI version compiled into this shared library.
 */
uint32_t ev_abi_version(void);

/**
 * Return a pointer to a null-terminated description of the last error on
 * this thread, or null if no error has been recorded.
 *
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *ev_last_error(void);

/**
 * Install (or clear, by passing null) a global log callback.
 *
 * All subsequent [`ev_sim_step`] calls drain `sim.pending_events()` and
 * forward a debug-formatted message per event.
 *
 * # Safety
 *
 * The caller guarantees that, while the callback remains installed, the
 * function pointer is valid to invoke.
 */
void ev_set_log_callback(struct Option_EvLogFn cb);

/**
 * Create a new simulation from a RON config on disk.
 *
 * Returns a newly allocated handle on success, or null on failure — call
 * [`ev_last_error`] for details.
 *
 * # Safety
 *
 * `config_path` must be a null-terminated UTF-8 C string, or null.
 */
struct EvSim *ev_sim_create(const char *config_path);

/**
 * Destroy a simulation handle. Null-safe.
 *
 * # Safety
 *
 * `handle` must either be null or a pointer returned by [`ev_sim_create`]
 * that has not already been destroyed.
 */
void ev_sim_destroy(struct EvSim *handle);

/**
 * Advance the simulation by one tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_step(struct EvSim *handle);

/**
 * Populate `out` with a borrowed view of the current simulation state.
 *
 * Pointers inside the frame are valid until the next `ev_sim_frame` call
 * on the same handle.
 *
 * # Safety
 *
 * `handle` and `out` must be valid, aligned, non-overlapping pointers.
 */
enum EvStatus ev_sim_frame(struct EvSim *handle, struct EvFrame *out);

/**
 * Query the best ETA to a stop across eligible elevators.
 *
 * `direction`: `-1` = Down, `0` = Either, `1` = Up. Returns
 * [`EvStatus::NotFound`] if no eligible elevator has `stop_entity_id`
 * queued; in that case the out-parameters are written as `(0, NaN)`.
 *
 * # Safety
 *
 * All pointers must be valid, aligned, and non-null.
 */
enum EvStatus ev_sim_best_eta(struct EvSim *handle,
                              uint64_t stop_entity_id,
                              int8_t direction,
                              uint64_t *out_elevator,
                              double *out_seconds);

/**
 * Replace the dispatch strategy for a group.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_strategy(struct EvSim *handle,
                                  uint32_t group_id,
                                  enum EvStrategy strategy);

/**
 * Press an up/down hall button at `stop_entity_id`. Games use this
 * for scripted NPCs, player input, or cutscene cues.
 *
 * `direction` uses `1` = Up, `-1` = Down.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_hall_button(struct EvSim *handle,
                                       uint64_t stop_entity_id,
                                       int8_t direction);

/**
 * Press a floor button inside a car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_car_button(struct EvSim *handle,
                                      uint64_t car_entity_id,
                                      uint64_t floor_entity_id);

/**
 * Pin the hall call at `(stop, direction)` to a specific car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_pin_assignment(struct EvSim *handle,
                                    uint64_t car_entity_id,
                                    uint64_t stop_entity_id,
                                    int8_t direction);

/**
 * Release a previous pin at `(stop, direction)`. No-op if none.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_unpin_assignment(struct EvSim *handle,
                                      uint64_t stop_entity_id,
                                      int8_t direction);

/**
 * Car currently assigned to serve the hall call at `(stop, direction)`.
 *
 * Writes the car's entity id to `out_elevator`, or `0` if no call
 * exists or no car is assigned.
 *
 * # Safety
 *
 * `handle` and `out_elevator` must be valid pointers.
 */
enum EvStatus ev_sim_assigned_car(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_elevator);

/**
 * Estimated ticks remaining before the assigned car reaches the call.
 *
 * Writes the tick count to `out_ticks`, or `u64::MAX` when no car is
 * assigned or no call exists at that `(stop, direction)`.
 *
 * # Safety
 *
 * `handle` and `out_ticks` must be valid pointers.
 */
enum EvStatus ev_sim_eta_for_call(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_ticks);

/**
 * Number of active hall calls across the whole simulation. Use as a
 * pre-check before allocating a buffer for
 * [`ev_sim_hall_calls_snapshot`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_hall_call_count(struct EvSim *handle);

/**
 * Snapshot a flat representation of every active hall call into `out`.
 *
 * The caller supplies a buffer of `capacity` [`EvHallCall`] entries;
 * the actual number written is returned in `out_written`. If
 * `capacity` is smaller than the live count, the buffer is filled
 * and the remainder is dropped.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` `EvHallCall`s.
 */
enum EvStatus ev_sim_hall_calls_snapshot(struct EvSim *handle,
                                         struct EvHallCall *out,
                                         uint32_t capacity,
                                         uint32_t *out_written);

/**
 * Drain pending hall-call / car-call / skip events into `out`.
 *
 * This is the FFI mirror of `Simulation::drain_events`, filtered to
 * the five events added by the hall-call work: every call produced
 * by the simulation is eventually delivered exactly once, then
 * removed from the internal queue. Call after `ev_sim_step` each
 * tick to catch new events; the buffer is caller-owned, so the
 * ownership contract differs from `ev_sim_frame`'s borrowed-view
 * path.
 *
 * Field meanings by [`EvEvent::kind`]:
 * - `HALL_BUTTON_PRESSED` / `HALL_CALL_ACKNOWLEDGED`: `stop`,
 *   `direction`, `tick`.
 * - `HALL_CALL_CLEARED`: `stop`, `direction`, `car`, `tick`.
 * - `CAR_BUTTON_PRESSED`: `car`, `floor`, `rider` (or `0` for
 *   synthetic presses), `tick`.
 * - `RIDER_SKIPPED`: `rider`, `car` (the elevator declined), `stop`
 *   (the skip site), `tick`.
 *
 * Unused fields for each kind are zeroed so the caller can inspect
 * a uniform struct layout. Other event kinds in the sim (door
 * transitions, rider spawns, etc.) are not surfaced — they'd
 * inflate the matrix and every FFI consumer would pay regardless
 * of whether they care. Future kinds extend the discriminator.
 *
 * ## Overflow handling — no silent drops
 *
 * If more than `capacity` events are pending, the first `capacity`
 * are written and the rest stay in an internal queue for the next
 * call. Callers can detect a truncated read two ways:
 * - `out_written == capacity` is *possibly* truncated. Call
 *   [`ev_sim_pending_event_count`] afterward; non-zero means more
 *   are queued.
 * - Drain in a loop until `ev_sim_pending_event_count` returns `0`.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvEvent`]s.
 */
enum EvStatus ev_sim_drain_events(struct EvSim *handle,
                                  struct EvEvent *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of events parked in the FFI event buffer plus any pending
 * in the underlying simulation queue. Use this to detect truncation
 * after [`ev_sim_drain_events`] or to size a buffer defensively.
 *
 * Calling this does not mutate the sim — it drains the sim's queue
 * into the FFI buffer so the count is accurate, but no events are
 * dropped and a subsequent `ev_sim_drain_events` call returns the
 * same set.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_pending_event_count(struct EvSim *handle);

#endif  /* ELEVATOR_FFI_H */
