/* Auto-generated by cbindgen. Do not edit. */

#ifndef ELEVATOR_FFI_H
#define ELEVATOR_FFI_H

#pragma once

/* Generated. Do not modify by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Current ABI version. Bumped for any breaking change to the C layout.
 *
 * **v5:** [`EvEvent`] gained a `tag` field carrying the opaque
 * per-rider tag (`Rider.tag`) for every rider-bearing event variant.
 * Consumers that want the back-pointer pattern this enables (set via
 * [`ev_sim_set_rider_tag`], read on [`ev_event_kind::RIDER_EXITED`] /
 * [`ev_event_kind::RIDER_DESPAWNED`] without re-querying a freed
 * rider) need to rebuild against v5.
 *
 * **v4** widened [`EvEvent`] from 7 fields to 14 to carry the full
 * payload of every core `Event` variant in a single drain pass. The
 * kind discriminator was extended from 9 known kinds to 49.
 */
#define EV_ABI_VERSION 5

/**
 * `Event::HallButtonPressed`. Fields: `stop`, `direction` (`1` =
 * up, `-1` = down), `tick`.
 */
#define HALL_BUTTON_PRESSED 1

/**
 * `Event::HallCallAcknowledged`. Fields: `stop`, `direction`,
 * `tick`.
 */
#define HALL_CALL_ACKNOWLEDGED 2

/**
 * `Event::HallCallCleared`. Fields: `stop`, `direction`, `car`
 * (the elevator that cleared the call by arriving), `tick`.
 */
#define HALL_CALL_CLEARED 3

/**
 * `Event::CarButtonPressed`. Fields: `car`, `floor` (the
 * requested stop), `rider` (or `0` for synthetic presses with no
 * associated rider), `tick`.
 */
#define CAR_BUTTON_PRESSED 4

/**
 * `Event::RiderSkipped`. Fields: `rider`, `car` (the elevator
 * they declined to board), `stop` (where the skip happened),
 * `tick`.
 */
#define RIDER_SKIPPED 5

/**
 * `Event::RiderSpawned`. Fields: `rider`, `stop` (origin), `floor`
 * (destination), `tick`.
 */
#define RIDER_SPAWNED 6

/**
 * `Event::RiderBoarded`. Fields: `rider`, `car` (elevator),
 * `tick`.
 */
#define RIDER_BOARDED 7

/**
 * `Event::RiderExited`. Fields: `rider`, `car` (elevator), `stop`
 * (where they exited), `tick`.
 */
#define RIDER_EXITED 8

/**
 * `Event::RiderAbandoned`. Fields: `rider`, `stop` (where they
 * gave up), `tick`.
 */
#define RIDER_ABANDONED 9

/**
 * `Event::ElevatorDeparted`. Fields: `car`, `stop` (from_stop), `tick`.
 */
#define ELEVATOR_DEPARTED 10

/**
 * `Event::ElevatorArrived`. Fields: `car`, `stop` (at_stop), `tick`.
 */
#define ELEVATOR_ARRIVED 11

/**
 * `Event::DoorOpened`. Fields: `car`, `tick`.
 */
#define DOOR_OPENED 12

/**
 * `Event::DoorClosed`. Fields: `car`, `tick`.
 */
#define DOOR_CLOSED 13

/**
 * `Event::PassingFloor`. Fields: `car`, `stop`, `direction` (`1` =
 * up, `-1` = down), `tick`.
 */
#define PASSING_FLOOR 14

/**
 * `Event::MovementAborted`. Fields: `car`, `stop` (brake_target),
 * `tick`.
 */
#define MOVEMENT_ABORTED 15

/**
 * `Event::RiderRejected`. Fields: `rider`, `car` (elevator),
 * `code1` (rejection reason — see [`crate::ev_rejection_reason`]),
 * `f1` (attempted_weight in kg, or `NaN` if no `RejectionContext`
 * was attached), `f2` (current_load on the elevator at rejection
 * time in kg, or `NaN`), `tick`.
 *
 * Capacity is intentionally not duplicated here — it lives on the
 * elevator entity (`EvElevatorView::capacity_kg`) and rarely
 * changes per-tick. Combine `f2` with the elevator's capacity for
 * the remaining-room view.
 */
#define RIDER_REJECTED 16

/**
 * `Event::RiderEjected`. Fields: `rider`, `car` (elevator), `stop`,
 * `tick`.
 */
#define RIDER_EJECTED 17

/**
 * `Event::ElevatorAssigned`. Fields: `car`, `stop`, `tick`.
 */
#define ELEVATOR_ASSIGNED 18

/**
 * `Event::StopAdded`. Fields: `stop`, `entity` (line), `group`, `tick`.
 */
#define STOP_ADDED 19

/**
 * `Event::ElevatorAdded`. Fields: `car`, `entity` (line), `group`,
 * `tick`.
 */
#define ELEVATOR_ADDED 20

/**
 * `Event::EntityDisabled`. Fields: `entity`, `tick`.
 */
#define ENTITY_DISABLED 21

/**
 * `Event::EntityEnabled`. Fields: `entity`, `tick`.
 */
#define ENTITY_ENABLED 22

/**
 * `Event::RouteInvalidated`. Fields: `rider`, `stop` (affected_stop),
 * `code1` (reason — see [`crate::ev_route_invalid_reason`]), `tick`.
 */
#define ROUTE_INVALIDATED 23

/**
 * `Event::RiderRerouted`. Fields: `rider`, `floor` (new_destination),
 * `tick`.
 */
#define RIDER_REROUTED 24

/**
 * `Event::RiderSettled`. Fields: `rider`, `stop`, `tick`.
 */
#define RIDER_SETTLED 25

/**
 * `Event::RiderDespawned`. Fields: `rider`, `tick`.
 */
#define RIDER_DESPAWNED 26

/**
 * `Event::LineAdded`. Fields: `entity` (line), `group`, `tick`.
 */
#define LINE_ADDED 27

/**
 * `Event::LineRemoved`. Fields: `entity` (line), `group`, `tick`.
 */
#define LINE_REMOVED 28

/**
 * `Event::LineReassigned`. Fields: `entity` (line), `group`
 * (new_group), `count` (old_group as u32), `tick`.
 */
#define LINE_REASSIGNED 29

/**
 * `Event::ElevatorReassigned`. Fields: `car`, `stop` (new_line),
 * `entity` (old_line), `tick`.
 */
#define ELEVATOR_REASSIGNED 30

/**
 * `Event::ElevatorRepositioning`. Fields: `car`, `stop` (to_stop),
 * `tick`.
 */
#define ELEVATOR_REPOSITIONING 31

/**
 * `Event::ElevatorRepositioned`. Fields: `car`, `stop` (at_stop),
 * `tick`.
 */
#define ELEVATOR_REPOSITIONED 32

/**
 * `Event::ElevatorRecalled`. Fields: `car`, `stop` (to_stop),
 * `tick`.
 */
#define ELEVATOR_RECALLED 33

/**
 * `Event::ServiceModeChanged`. Fields: `car`, `code1` (new mode —
 * same encoding as [`crate::EvServiceMode`]), `code2` (previous
 * mode), `tick`.
 */
#define SERVICE_MODE_CHANGED 34

/**
 * `Event::EnergyConsumed`. Fields: `car`, `f1` (consumed kJ), `f2`
 * (regenerated kJ), `tick`. Requires the `energy` feature on
 * `elevator-core`; emitted as `UNKNOWN` if the feature is off.
 */
#define ENERGY_CONSUMED 35

/**
 * `Event::CapacityChanged`. Fields: `car`, `f1` (current_load), `f2`
 * (capacity), `tick`.
 */
#define CAPACITY_CHANGED 36

/**
 * `Event::ElevatorIdle`. Fields: `car`, `stop` (at_stop, `0` when
 * the elevator is idle mid-shaft), `tick`.
 */
#define ELEVATOR_IDLE 37

/**
 * `Event::DirectionIndicatorChanged`. Fields: `car`, `code1` (1 if
 * going_up else 0), `code2` (1 if going_down else 0), `tick`.
 */
#define DIRECTION_INDICATOR_CHANGED 38

/**
 * `Event::ElevatorRemoved`. Fields: `car`, `entity` (line),
 * `group`, `tick`.
 */
#define ELEVATOR_REMOVED 39

/**
 * `Event::DestinationQueued`. Fields: `car`, `stop`, `tick`.
 */
#define DESTINATION_QUEUED 40

/**
 * `Event::StopRemoved`. Fields: `stop`, `tick`.
 */
#define STOP_REMOVED 41

/**
 * `Event::DoorCommandQueued`. Fields: `car`, `code1` (door
 * command — see [`crate::ev_door_command`]), `count` (hold ticks for
 * `HoldOpen`, `0` for other commands), `tick`.
 */
#define DOOR_COMMAND_QUEUED 42

/**
 * `Event::DoorCommandApplied`. Fields: `car`, `code1` (door
 * command), `count` (hold ticks for `HoldOpen`), `tick`.
 */
#define DOOR_COMMAND_APPLIED 43

/**
 * `Event::ElevatorUpgraded`. Fields: `car`, `code1` (field — see
 * [`crate::ev_upgrade_field`]), `f1` (new value when float, NaN
 * otherwise), `count` (new value when integral ticks, `u32::MAX`
 * otherwise), `tick`.
 */
#define ELEVATOR_UPGRADED 44

/**
 * `Event::ManualVelocityCommanded`. Fields: `car`, `f1` (target
 * velocity, `NaN` when the command clears the target), `tick`.
 */
#define MANUAL_VELOCITY_COMMANDED 45

/**
 * `Event::SnapshotDanglingReference`. Fields: `entity` (stale id),
 * `tick`.
 */
#define SNAPSHOT_DANGLING_REFERENCE 46

/**
 * `Event::RepositionStrategyNotRestored`. Fields: `group`, `tick`.
 */
#define REPOSITION_STRATEGY_NOT_RESTORED 47

/**
 * `Event::DispatchConfigNotRestored`. Fields: `group`, `tick`.
 */
#define DISPATCH_CONFIG_NOT_RESTORED 48

/**
 * `Event::ResidentsAtRemovedStop`. Fields: `stop`, `count`
 * (residents.len()), `tick`. The actual rider list is **not**
 * surfaced — this signal is informational; consumers needing the
 * list should query `ev_sim_residents_at` before the stop is
 * removed.
 */
#define RESIDENTS_AT_REMOVED_STOP 49

/**
 * Reserved sentinel for variants the FFI does not yet mirror.
 * Consumers should ignore events with this kind to stay
 * forward-compatible.
 */
#define UNKNOWN 0

/**
 * `RejectionReason::OverCapacity`.
 */
#define OVER_CAPACITY 0

/**
 * `RejectionReason::PreferenceBased`.
 */
#define PREFERENCE_BASED 1

/**
 * `RejectionReason::AccessDenied`.
 */
#define ACCESS_DENIED 2

/**
 * `RouteInvalidReason::StopDisabled`.
 */
#define STOP_DISABLED 0

/**
 * `RouteInvalidReason::NoAlternative`.
 */
#define NO_ALTERNATIVE 1

/**
 * `DoorCommand::Open`.
 */
#define OPEN 0

/**
 * `DoorCommand::Close`.
 */
#define CLOSE 1

/**
 * `DoorCommand::HoldOpen`.
 */
#define HOLD_OPEN 2

/**
 * `DoorCommand::CancelHold`.
 */
#define CANCEL_HOLD 3

/**
 * `UpgradeField::MaxSpeed`.
 */
#define MAX_SPEED 0

/**
 * `UpgradeField::Acceleration`.
 */
#define ACCELERATION 1

/**
 * `UpgradeField::Deceleration`.
 */
#define DECELERATION 2

/**
 * `UpgradeField::WeightCapacity`.
 */
#define WEIGHT_CAPACITY 3

/**
 * `UpgradeField::DoorTransitionTicks`.
 */
#define DOOR_TRANSITION_TICKS 4

/**
 * `UpgradeField::DoorOpenTicks`.
 */
#define DOOR_OPEN_TICKS 5

/**
 * Status code returned by every FFI entrypoint.
 */
typedef enum EvStatus {
    /**
     * Operation succeeded.
     */
    Ok = 0,
    /**
     * A required pointer argument was null.
     */
    NullArg = 1,
    /**
     * A C string argument was not valid UTF-8.
     */
    InvalidUtf8 = 2,
    /**
     * The config file could not be read from disk.
     */
    ConfigLoad = 3,
    /**
     * The config file failed to parse as RON.
     */
    ConfigParse = 4,
    /**
     * [`SimulationBuilder::build`] returned an error.
     */
    BuildFailed = 5,
    /**
     * The requested entity, group, or resource was not found.
     */
    NotFound = 6,
    /**
     * An argument was structurally valid but semantically rejected.
     */
    InvalidArg = 7,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    Panic = 99,
} EvStatus;

/**
 * Built-in dispatch strategy identifier.
 *
 * ABI v3 added `Destination` and `Rsr`; consumers compiled against
 * v2 will see [`ev_abi_version`] return `3` and refuse to load.
 */
typedef enum EvStrategy {
    /**
     * SCAN — sweep end-to-end.
     */
    Scan = 0,
    /**
     * LOOK — reverse at last request.
     */
    Look = 1,
    /**
     * Nearest-car.
     */
    NearestCar = 2,
    /**
     * Estimated time to destination.
     */
    Etd = 3,
    /**
     * Destination dispatch (lobby kiosk, hall-button mode = Destination).
     */
    Destination = 4,
    /**
     * RSR — composite cost-stack with stock weights.
     */
    Rsr = 5,
    /**
     * Custom (non-builtin) strategy. Passed only as an output value
     * from [`ev_sim_strategy_id`]; passing it to a setter returns
     * `EvStatus::InvalidArg` since FFI consumers cannot register
     * custom strategies.
     */
    Custom = 99,
} EvStrategy;

/**
 * Built-in reposition strategy identifier (ABI v3+).
 *
 * Mirrors [`elevator_core::dispatch::BuiltinReposition`]. `Custom` is
 * an output-only sentinel for non-built-in strategies registered via
 * the Rust API; FFI consumers passing `Custom` to a setter receive
 * `EvStatus::InvalidArg`.
 */
typedef enum EvReposition {
    /**
     * Distribute idle elevators evenly across stops.
     */
    SpreadEvenly = 0,
    /**
     * Return idle elevators to a configured home stop.
     */
    ReturnToLobby = 1,
    /**
     * Position near stops with historically high demand.
     */
    DemandWeighted = 2,
    /**
     * Keep idle elevators where they are.
     */
    NearestIdle = 3,
    /**
     * Pre-position cars near stops with the highest recent arrival rate.
     */
    PredictiveParking = 4,
    /**
     * Mode-gated picker between `ReturnToLobby` / `PredictiveParking`.
     */
    Adaptive = 5,
    /**
     * Custom (output-only).
     */
    Custom = 99,
} EvReposition;

/**
 * Operational service mode for an elevator. Mirrors
 * [`elevator_core::components::ServiceMode`].
 */
typedef enum EvServiceMode {
    /**
     * Normal operation: dispatch assigns stops, doors auto-cycle.
     */
    Normal = 0,
    /**
     * Excluded from dispatch and repositioning. Consumer drives movement.
     */
    Independent = 1,
    /**
     * Reduced speed, doors hold open indefinitely.
     */
    Inspection = 2,
    /**
     * Driven by direct velocity commands. Doors follow manual API.
     */
    Manual = 3,
    /**
     * Shut down: excluded from dispatch, no auto-boarding, fully inert
     * once idle.
     */
    OutOfService = 4,
} EvServiceMode;

/**
 * Opaque simulation handle. Layout is not part of the ABI.
 */
typedef struct EvSim EvSim;

typedef struct Option_EvLogFn Option_EvLogFn;

/**
 * View of a single elevator at the current tick.
 */
typedef struct EvElevatorView {
    /**
     * Elevator entity id (raw slotmap `as_ffi()`).
     */
    uint64_t entity_id;
    /**
     * Group id this elevator belongs to (`u32::MAX` if orphaned).
     */
    uint32_t group_id;
    /**
     * Line (shaft/tether) entity id.
     */
    uint64_t line_id;
    /**
     * [`ElevatorPhase`] tag: 0 `Idle`, 1 `MovingToStop`, 2 `Repositioning`,
     * 3 `DoorOpening`, 4 `Loading`, 5 `DoorClosing`, 6 `Stopped`.
     */
    uint8_t phase;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Instantaneous velocity (+ up, - down).
     */
    double velocity;
    /**
     * Current stop (0 if not at a stop / moving).
     */
    uint64_t current_stop_id;
    /**
     * Target stop (0 if idle).
     */
    uint64_t target_stop_id;
    /**
     * Number of riders on board.
     */
    uint32_t occupancy;
    /**
     * Weight capacity in kg.
     */
    double capacity_kg;
    /**
     * [`DoorState`] tag: 0 `Closed`, 1 `Opening`, 2 `Open`, 3 `Closing`.
     */
    uint8_t door_state;
    /**
     * Direction indicator: 1 if the "going up" lamp is lit, 0 otherwise.
     */
    uint8_t going_up;
    /**
     * Direction indicator: 1 if the "going down" lamp is lit, 0 otherwise.
     */
    uint8_t going_down;
} EvElevatorView;

/**
 * View of a single stop at the current tick.
 */
typedef struct EvStopView {
    /**
     * Stop entity id.
     */
    uint64_t entity_id;
    /**
     * Config-level stop id (as declared in the RON file).
     */
    uint32_t stop_id;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Number of riders currently waiting at this stop.
     */
    uint32_t waiting;
    /**
     * Number of resident (parked) riders at this stop.
     */
    uint32_t residents;
    /**
     * Number of riders who abandoned waiting at this stop.
     */
    uint32_t abandoned;
    /**
     * UTF-8 name bytes borrowed from the frame's arena.
     */
    const uint8_t *name_ptr;
    /**
     * Length in bytes of the name slice at [`Self::name_ptr`].
     */
    uintptr_t name_len;
} EvStopView;

/**
 * View of a single rider at the current tick.
 */
typedef struct EvRiderView {
    /**
     * Rider entity id.
     */
    uint64_t entity_id;
    /**
     * [`RiderPhase`] tag: 0 `Waiting`, 1 `Boarding`, 2 `Riding`, 3 `Exiting`,
     * 4 `Walking`, 5 `Arrived`, 6 `Abandoned`, 7 `Resident`.
     */
    uint8_t phase;
    /**
     * Origin / current stop entity id (0 if none).
     */
    uint64_t origin_stop_id;
    /**
     * Final destination stop entity id (0 if no route).
     */
    uint64_t destination_stop_id;
    /**
     * Elevator carrying the rider (0 if not aboard).
     */
    uint64_t elevator_id;
} EvRiderView;

/**
 * Aggregate metrics at the current tick.
 */
typedef struct EvMetricsView {
    /**
     * Cumulative riders delivered.
     */
    uint64_t total_delivered;
    /**
     * Cumulative riders who abandoned.
     */
    uint64_t total_abandoned;
    /**
     * Average wait time (seconds).
     */
    double avg_wait_seconds;
    /**
     * Average ride time (seconds).
     */
    double avg_ride_seconds;
    /**
     * Current simulation tick.
     */
    uint64_t current_tick;
} EvMetricsView;

/**
 * Borrowed per-tick snapshot. All slice pointers are valid until the next
 * call to [`ev_sim_frame`] on the same handle.
 */
typedef struct EvFrame {
    /**
     * Pointer to contiguous elevator views.
     */
    const struct EvElevatorView *elevators;
    /**
     * Number of elements at [`Self::elevators`].
     */
    uintptr_t elevator_count;
    /**
     * Pointer to contiguous stop views.
     */
    const struct EvStopView *stops;
    /**
     * Number of elements at [`Self::stops`].
     */
    uintptr_t stop_count;
    /**
     * Pointer to contiguous rider views.
     */
    const struct EvRiderView *riders;
    /**
     * Number of elements at [`Self::riders`].
     */
    uintptr_t rider_count;
    /**
     * Aggregate metrics snapshot.
     */
    struct EvMetricsView metrics;
} EvFrame;

/**
 * One `(line, car)` assignment on a hall call. Read by
 * [`ev_sim_assigned_cars_by_line`].
 */
typedef struct EvAssignment {
    /**
     * Line entity id the car runs on.
     */
    uint64_t line_entity_id;
    /**
     * Car entity id assigned to this line's share of the call.
     */
    uint64_t car_entity_id;
} EvAssignment;

/**
 * C-ABI-flat projection of a `HallCall` for FFI consumers.
 */
typedef struct EvHallCall {
    /**
     * Stop entity id (same encoding as elsewhere in the FFI).
     */
    uint64_t stop_entity_id;
    /**
     * `1` = Up, `-1` = Down.
     */
    int8_t direction;
    /**
     * Tick at which the button was pressed.
     */
    uint64_t press_tick;
    /**
     * Tick at which the call was acknowledged; `u64::MAX` if pending.
     */
    uint64_t acknowledged_at;
    /**
     * Car currently assigned to serve the call; `0` if none.
     *
     * At a stop served by multiple lines (e.g. a sky-lobby) a call can
     * hold one assignment per line. This field mirrors the FFI's
     * historical single-value shape and surfaces whichever entry has
     * the numerically smallest line-entity id. Use
     * [`ev_sim_assigned_cars_by_line`] to read every line's entry.
     */
    uint64_t assigned_car;
    /**
     * Destination stop entity id in DCS (`HallCallMode::Destination`)
     * mode, or `0` when the call has no destination (Classic mode,
     * or no kiosk entry yet). Matches `HallCall::destination`.
     */
    uint64_t destination_entity_id;
    /**
     * `1` when pinned, `0` otherwise.
     */
    uint8_t pinned;
    /**
     * Number of riders aggregated onto this call.
     */
    uint32_t pending_rider_count;
} EvHallCall;

/**
 * C-ABI-flat projection of every `Event` variant emitted by the
 * simulation.
 *
 * The `kind` discriminator picks which fields are meaningful — see
 * [`ev_event_kind`] for the kind constants and per-kind field map.
 * Entity-id fields use `0` to mean "not applicable for this kind"
 * (real entity ids are never zero under the FFI encoding).
 *
 * **ABI v4** widened this from 7 to 14 fields to cover the full payload
 * of every core variant in a single drain pass; consumers that bound
 * against v3 must rebuild and check [`EV_ABI_VERSION`].
 */
typedef struct EvEvent {
    /**
     * Event kind discriminator. Values outside [`ev_event_kind`] are
     * reserved — surface as [`UNKNOWN`](ev_event_kind::UNKNOWN) and
     * ignore for forward compatibility.
     */
    uint8_t kind;
    /**
     * Direction code: `1` = Up, `-1` = Down, `0` = N/A. Used by hall-call
     * events and `PassingFloor`.
     */
    int8_t direction;
    /**
     * Primary enum payload. Meaning depends on `kind` (see the kind
     * docs for each event). `0` when not applicable.
     */
    uint8_t code1;
    /**
     * Secondary enum payload. Meaning depends on `kind`. `0` when not
     * applicable.
     */
    uint8_t code2;
    /**
     * Group id payload (for `LineAdded`, `LineRemoved`, `LineReassigned`,
     * `StopAdded`, `ElevatorAdded`, `ElevatorRemoved`,
     * `RepositionStrategyNotRestored`, `DispatchConfigNotRestored`).
     * `0` for kinds that don't carry a group.
     */
    uint32_t group;
    /**
     * Tick the event was emitted on.
     */
    uint64_t tick;
    /**
     * Stop entity id. Meaning depends on the kind.
     */
    uint64_t stop;
    /**
     * Car/elevator entity id. Meaning depends on the kind.
     */
    uint64_t car;
    /**
     * Rider entity id.
     */
    uint64_t rider;
    /**
     * Destination/floor entity id. Used by `CarButtonPressed` (the
     * requested floor), `RiderSpawned` (rider's destination), and
     * `RiderRerouted` (new_destination).
     */
    uint64_t floor;
    /**
     * Generic entity id slot for variants that carry an entity that
     * doesn't fit `stop`/`car`/`rider`/`floor` — `EntityDisabled`,
     * `EntityEnabled`, `LineAdded` (line), `StopAdded` (line),
     * `ElevatorReassigned` (old_line), `SnapshotDanglingReference`,
     * etc. `0` when not applicable.
     */
    uint64_t entity;
    /**
     * Count payload. Used by `ResidentsAtRemovedStop` (rider count),
     * `ElevatorUpgraded` (new value when integral ticks, `u64::MAX`
     * when float), and `LineReassigned` (old group id encoded as u64
     * for callers that want both groups). `0` when not applicable.
     */
    uint64_t count;
    /**
     * Primary float payload. Used by `EnergyConsumed` (consumed kJ),
     * `CapacityChanged` (current_load), `ElevatorUpgraded` (new value
     * when float), and `ManualVelocityCommanded` (target velocity,
     * `NaN` when the command clears the target).
     */
    double f1;
    /**
     * Secondary float payload. Used by `EnergyConsumed` (regenerated
     * kJ) and `CapacityChanged` (capacity).
     */
    double f2;
    /**
     * Opaque consumer tag for the rider involved in this event,
     * mirroring [`Rider::tag()`](elevator_core::components::Rider::tag).
     * Populated for every rider-bearing variant — `RiderSpawned`,
     * `RiderBoarded`, `RiderExited`, `RiderRejected`, `RiderAbandoned`,
     * `RiderEjected`, `RiderSettled`, `RiderDespawned`, `RiderRerouted`,
     * `RiderSkipped`, `RouteInvalidated`, plus `CarButtonPressed` when
     * the press came from a real rider. `0` when not applicable
     * (non-rider event, or rider untagged, or synthetic
     * [`CarButtonPressed`](ev_event_kind::CAR_BUTTON_PRESSED) with no
     * associated rider).
     */
    uint64_t tag;
} EvEvent;

/**
 * A single log message returned by [`ev_drain_log_messages`].
 *
 * `msg_ptr` borrows from an internal buffer owned by the handle and
 * remains valid until the next [`ev_drain_log_messages`] call on the
 * same handle. The bytes are UTF-8 and are **not** null-terminated;
 * use `msg_len` to bound the read.
 */
typedef struct EvLogMessage {
    /**
     * Severity level (0 = trace, 1 = debug, 2 = info, 3 = warn, 4 = error).
     */
    uint8_t level;
    /**
     * Wall-clock timestamp at message ingestion, in nanoseconds since
     * the Unix epoch. `0` if the host clock is unavailable.
     */
    int64_t ts_ns;
    /**
     * Pointer to UTF-8 message bytes. Borrowed; not null-terminated.
     */
    const uint8_t *msg_ptr;
    /**
     * Length of `msg_ptr` in bytes.
     */
    uint32_t msg_len;
} EvLogMessage;

/**
 * Repr-C mirror of [`elevator_core::sim::ElevatorParams`].
 *
 * Sentinel encoding:
 * - `bypass_load_up_pct` and `bypass_load_down_pct`: NaN encodes
 *   [`Option::None`]; any finite value is treated as `Some(v)`.
 *
 * Use [`ev_sim_default_elevator_params`] to populate this struct with
 * the same defaults as `ElevatorParams::default()`. Callers should
 * supply `restricted_stops` separately as a `(*const u64, count)` pair
 * to [`ev_sim_add_elevator`].
 */
typedef struct EvElevatorParams {
    /**
     * Maximum travel speed (distance/tick); must be positive and finite.
     */
    double max_speed;
    /**
     * Acceleration rate (distance/tick^2); must be positive and finite.
     */
    double acceleration;
    /**
     * Deceleration rate (distance/tick^2); must be positive and finite.
     */
    double deceleration;
    /**
     * Maximum weight the car can carry; must be positive and finite.
     */
    double weight_capacity;
    /**
     * Ticks for a door open/close transition; must be > 0.
     */
    uint32_t door_transition_ticks;
    /**
     * Ticks the door stays fully open; must be > 0.
     */
    uint32_t door_open_ticks;
    /**
     * Speed multiplier for Inspection mode; must satisfy `0.0 < x <= 1.0`.
     */
    double inspection_speed_factor;
    /**
     * Full-load bypass threshold for upward pickups, or `NaN` for None.
     * When non-NaN, must satisfy `0.0 <= x <= 1.0`.
     */
    double bypass_load_up_pct;
    /**
     * Full-load bypass threshold for downward pickups, or `NaN` for None.
     * When non-NaN, must satisfy `0.0 <= x <= 1.0`.
     */
    double bypass_load_down_pct;
} EvElevatorParams;

/**
 * C-ABI-flat projection of a `CarCall` for FFI consumers.
 *
 * Mirrors [`elevator_core::components::CarCall`] field-for-field with
 * `EntityId` slots flattened to `u64` and the `pending_riders` Vec
 * surfaced as a count (call [`ev_sim_car_call_pending_riders`] to read
 * the actual rider list).
 */
typedef struct EvCarCall {
    /**
     * Elevator the button was pressed inside.
     */
    uint64_t car_entity_id;
    /**
     * Stop the button requests.
     */
    uint64_t floor_entity_id;
    /**
     * Tick the button was pressed.
     */
    uint64_t press_tick;
    /**
     * Tick dispatch first saw this call (after ack latency).
     * `u64::MAX` while still pending acknowledgement.
     */
    uint64_t acknowledged_at;
    /**
     * Ticks the controller takes to acknowledge this call.
     */
    uint32_t ack_latency_ticks;
    /**
     * Number of riders aggregated onto this call. Read the actual
     * rider ids via [`ev_sim_car_call_pending_riders`].
     */
    uint32_t pending_rider_count;
} EvCarCall;

/**
 * Full repr-C mirror of [`elevator_core::metrics::Metrics`].
 *
 * Time fields stay in **ticks** (not seconds) — multiply by [`ev_sim_dt`]
 * for real-time. The narrower [`EvMetricsView`] embedded in [`EvFrame`]
 * is kept for backward compatibility; new code should prefer this struct.
 */
typedef struct EvMetrics {
    /**
     * Cumulative riders delivered.
     */
    uint64_t total_delivered;
    /**
     * Cumulative riders who abandoned.
     */
    uint64_t total_abandoned;
    /**
     * Total riders spawned.
     */
    uint64_t total_spawned;
    /**
     * Riders settled as residents.
     */
    uint64_t total_settled;
    /**
     * Riders rerouted from resident phase.
     */
    uint64_t total_rerouted;
    /**
     * Riders delivered in the current throughput window.
     */
    uint64_t throughput;
    /**
     * Average wait time in ticks (spawn → board).
     */
    double avg_wait_ticks;
    /**
     * Maximum wait time observed in ticks.
     */
    uint64_t max_wait_ticks;
    /**
     * Average ride time in ticks (board → exit).
     */
    double avg_ride_ticks;
    /**
     * Average elevator utilization (0.0..=1.0).
     */
    double avg_utilization;
    /**
     * Abandonment rate (0.0..=1.0).
     */
    double abandonment_rate;
    /**
     * Total distance traveled by all elevators.
     */
    double total_distance;
    /**
     * Total rounded-floor crossings across all elevators.
     */
    uint64_t total_moves;
    /**
     * Distance traveled while repositioning (subset of `total_distance`).
     */
    double reposition_distance;
} EvMetrics;

/**
 * Per-tag metric snapshot. Mirrors
 * [`elevator_core::tagged_metrics::TaggedMetric`].
 */
typedef struct EvTaggedMetric {
    /**
     * Average wait time in ticks for tagged riders.
     */
    double avg_wait_ticks;
    /**
     * Maximum wait time observed in ticks for tagged riders.
     */
    uint64_t max_wait_ticks;
    /**
     * Total riders delivered carrying this tag.
     */
    uint64_t total_delivered;
    /**
     * Total riders abandoned carrying this tag.
     */
    uint64_t total_abandoned;
    /**
     * Total riders spawned carrying this tag.
     */
    uint64_t total_spawned;
} EvTaggedMetric;

/**
 * Return the ABI version compiled into this shared library.
 */
uint32_t ev_abi_version(void);

/**
 * Return a pointer to a null-terminated description of the last error on
 * this thread, or null if no error has been recorded.
 *
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *ev_last_error(void);

/**
 * Install (or clear, by passing null) a global log callback.
 *
 * All subsequent [`ev_sim_step`] calls drain `sim.pending_events()` and
 * forward a debug-formatted message per event.
 *
 * # Safety
 *
 * The caller guarantees that, while the callback remains installed, the
 * function pointer is valid to invoke.
 */
void ev_set_log_callback(struct Option_EvLogFn cb);

/**
 * Create a new simulation from a RON config on disk.
 *
 * Returns a newly allocated handle on success, or null on failure — call
 * [`ev_last_error`] for details.
 *
 * # Safety
 *
 * `config_path` must be a null-terminated UTF-8 C string, or null.
 */
struct EvSim *ev_sim_create(const char *config_path);

/**
 * Destroy a simulation handle. Null-safe.
 *
 * # Safety
 *
 * `handle` must either be null or a pointer returned by [`ev_sim_create`]
 * that has not already been destroyed.
 */
void ev_sim_destroy(struct EvSim *handle);

/**
 * Advance the simulation by one tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_step(struct EvSim *handle);

/**
 * Populate `out` with a borrowed view of the current simulation state.
 *
 * Pointers inside the frame are valid until the next `ev_sim_frame` call
 * on the same handle.
 *
 * # Safety
 *
 * `handle` and `out` must be valid, aligned, non-overlapping pointers.
 */
enum EvStatus ev_sim_frame(struct EvSim *handle, struct EvFrame *out);

/**
 * Query the best ETA to a stop across eligible elevators.
 *
 * `direction`: `-1` = Down, `0` = Either, `1` = Up. Returns
 * [`EvStatus::NotFound`] if no eligible elevator has `stop_entity_id`
 * queued; in that case the out-parameters are written as `(0, NaN)`.
 *
 * # Safety
 *
 * All pointers must be valid, aligned, and non-null.
 */
enum EvStatus ev_sim_best_eta(struct EvSim *handle,
                              uint64_t stop_entity_id,
                              int8_t direction,
                              uint64_t *out_elevator,
                              double *out_seconds);

/**
 * Replace the dispatch strategy for a group.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_strategy(struct EvSim *handle,
                                  uint32_t group_id,
                                  enum EvStrategy strategy);

/**
 * Remove the reposition strategy from `group_id`. Idle elevators stay
 * where they parked instead of moving toward a target.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_reposition(struct EvSim *handle, uint32_t group_id);

/**
 * Get the dispatch strategy currently active on `group_id`. Writes the
 * result to `*out_strategy`. Returns `EvStatus::NotFound` if the group
 * has no registered strategy (or doesn't exist).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_strategy` must be a writable [`EvStrategy`] pointer.
 */
enum EvStatus ev_sim_strategy_id(struct EvSim *handle,
                                 uint32_t group_id,
                                 enum EvStrategy *out_strategy);

/**
 * Set the reposition strategy on `group_id`. Pass [`EvReposition::Custom`]
 * returns `InvalidArg` — FFI consumers cannot register custom strategies.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_reposition(struct EvSim *handle,
                                    uint32_t group_id,
                                    enum EvReposition strategy);

/**
 * Get the reposition strategy currently set on `group_id`. Returns
 * `EvStatus::NotFound` if the group has no reposition strategy.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_strategy` must be a writable [`EvReposition`] pointer.
 */
enum EvStatus ev_sim_reposition_id(struct EvSim *handle,
                                   uint32_t group_id,
                                   enum EvReposition *out_strategy);

/**
 * Step the simulation forward up to `max_ticks` ticks.
 *
 * Stops early if the world becomes "quiet" (no in-flight riders, no
 * pending hall calls, all cars idle). Writes the actual tick count
 * to `*out_ticks_run` on both success and timeout.
 *
 * Returns `EvStatus::Ok` if the world quieted within `max_ticks`,
 * `EvStatus::InvalidArg` if it failed to quiet (loop guard).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_ticks_run` must be a writable `u64`.
 */
enum EvStatus ev_sim_run_until_quiet(struct EvSim *handle,
                                     uint64_t max_ticks,
                                     uint64_t *out_ticks_run);

/**
 * Press an up/down hall button at `stop_entity_id`. Games use this
 * for scripted NPCs, player input, or cutscene cues.
 *
 * `direction` uses `1` = Up, `-1` = Down.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_hall_button(struct EvSim *handle,
                                       uint64_t stop_entity_id,
                                       int8_t direction);

/**
 * Press a floor button inside a car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_car_button(struct EvSim *handle,
                                      uint64_t car_entity_id,
                                      uint64_t floor_entity_id);

/**
 * Pin the hall call at `(stop, direction)` to a specific car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_pin_assignment(struct EvSim *handle,
                                    uint64_t car_entity_id,
                                    uint64_t stop_entity_id,
                                    int8_t direction);

/**
 * Release a previous pin at `(stop, direction)`. No-op if none.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_unpin_assignment(struct EvSim *handle,
                                      uint64_t stop_entity_id,
                                      int8_t direction);

/**
 * Car currently assigned to serve the hall call at `(stop, direction)`.
 *
 * Writes the car's entity id to `out_elevator`, or `0` if no call
 * exists or no car is assigned.
 *
 * # Safety
 *
 * `handle` and `out_elevator` must be valid pointers.
 */
enum EvStatus ev_sim_assigned_car(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_elevator);

/**
 * Per-line car assignments at the hall call `(stop, direction)`.
 *
 * Writes up to `capacity` [`EvAssignment`] records to `out` and the
 * number actually written to `out_written`. Lines with no assignment
 * are omitted. Iteration order follows the `BTreeMap` keyed by line
 * entity id — stable across ticks.
 *
 * Use [`ev_sim_assigned_car`] for the single-value convenience view;
 * this call is for consumers that need every line's assignment at a
 * multi-line stop (e.g. a sky-lobby served by low, high, and express
 * banks).
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvAssignment`]s.
 */
enum EvStatus ev_sim_assigned_cars_by_line(struct EvSim *handle,
                                           uint64_t stop_entity_id,
                                           int8_t direction,
                                           struct EvAssignment *out,
                                           uint32_t capacity,
                                           uint32_t *out_written);

/**
 * Estimated ticks remaining before the assigned car reaches the call.
 *
 * Writes the tick count to `out_ticks`, or `u64::MAX` when no car is
 * assigned or no call exists at that `(stop, direction)`.
 *
 * # Safety
 *
 * `handle` and `out_ticks` must be valid pointers.
 */
enum EvStatus ev_sim_eta_for_call(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_ticks);

/**
 * Number of active hall calls across the whole simulation. Use as a
 * pre-check before allocating a buffer for
 * [`ev_sim_hall_calls_snapshot`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_hall_call_count(struct EvSim *handle);

/**
 * Snapshot a flat representation of every active hall call into `out`.
 *
 * Caller-owned buffer with probe-then-fill semantics: `out_written`
 * is populated with the **required** slot count regardless of whether
 * the buffer fits, so callers can probe with `(null, 0)` to size a
 * real buffer.
 *
 * Returns:
 * - [`EvStatus::Ok`] when all calls fit in `capacity` (`out_written
 *   <= capacity`); the first `out_written` slots of `out` are
 *   populated.
 * - [`EvStatus::InvalidArg`] when the buffer is too small;
 *   `out_written` carries the required slot count and no slot of
 *   `out` is written. [`ev_last_error`] carries a diagnostic string
 *   **only** when `capacity > 0` — the documented `(null, 0)` probe
 *   leaves the last-error slot clear so callers using
 *   [`ev_last_error`] for diagnostics don't see a false "programmer
 *   mistake" after a deliberate size query.
 *
 * **ABI v4 contract change:** prior versions silently truncated to
 * `capacity` and returned `Ok` regardless. Callers that previously
 * passed an under-sized buffer and ignored the count must now
 * either grow the buffer or check for `InvalidArg`. Use
 * [`ev_sim_hall_call_count`] for size-only probes when the buffer
 * pattern feels heavyweight.
 *
 * # Safety
 *
 * `handle` and `out_written` must be valid pointers. `out` must point
 * to a buffer of at least `capacity` [`EvHallCall`]s when `capacity > 0`,
 * and may be null when `capacity == 0` (probe pass).
 */
enum EvStatus ev_sim_hall_calls_snapshot(struct EvSim *handle,
                                         struct EvHallCall *out,
                                         uint32_t capacity,
                                         uint32_t *out_written);

/**
 * Drain pending events into `out`.
 *
 * Every event produced by the simulation is eventually delivered
 * exactly once, then removed from the internal queue. Call after
 * `ev_sim_step` each tick to catch new events.
 *
 * As of ABI v4 the FFI surfaces every public core `Event` variant —
 * 49 kinds in total. The per-kind field map (which `EvEvent` slots
 * carry meaningful data) lives on each constant in the
 * [`ev_event_kind`] module. Variants the FFI hasn't enumerated yet
 * surface as [`UNKNOWN`](ev_event_kind::UNKNOWN) so consumers stay
 * forward-compatible.
 *
 * Unused fields for each kind are zeroed (numeric slots: `0`; floats:
 * `0.0`) so the caller can inspect a uniform struct layout. Variants
 * that carry an `Option<f64>` use `NaN` instead of `0.0` to
 * disambiguate "no value" from "value of zero" — see the relevant
 * kind's docs.
 *
 * ## Overflow handling — no silent drops
 *
 * If more than `capacity` events are pending, the first `capacity`
 * are written and the rest stay in an internal queue for the next
 * call. Callers can detect a truncated read two ways:
 * - `out_written == capacity` is *possibly* truncated. Call
 *   [`ev_sim_pending_event_count`] afterward; non-zero means more
 *   are queued.
 * - Drain in a loop until `ev_sim_pending_event_count` returns `0`.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvEvent`]s.
 */
enum EvStatus ev_sim_drain_events(struct EvSim *handle,
                                  struct EvEvent *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Drain queued log messages into a caller-provided buffer.
 *
 * Each [`EvLogMessage::msg_ptr`] borrows from an internal buffer
 * owned by the handle and remains valid only until the next
 * `ev_drain_log_messages` call on the same handle (mirrors the
 * [`ev_sim_frame`] borrow rule). UTF-8 bytes are not
 * null-terminated; bound the read with `msg_len`.
 *
 * If more messages are queued than `capacity`, the surplus stays in
 * the internal queue for the next call. Drain in a loop until
 * `out_written < capacity` to consume the full backlog.
 *
 * Messages are recorded for every consumer regardless of whether a
 * callback is installed via [`ev_set_log_callback`], so polling
 * hosts (e.g. `GameMaker`, which cannot pass C function pointers) get
 * the same stream as callback hosts. A consumer that uses neither
 * path should drain occasionally to bound queue growth.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvLogMessage`]s.
 */
enum EvStatus ev_drain_log_messages(struct EvSim *handle,
                                    struct EvLogMessage *out,
                                    uint32_t capacity,
                                    uint32_t *out_written);

/**
 * Number of log messages parked in the FFI buffer awaiting a
 * [`ev_drain_log_messages`] call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_pending_log_message_count(struct EvSim *handle);

/**
 * Number of events parked in the FFI event buffer plus any pending
 * in the underlying simulation queue. Use this to detect truncation
 * after [`ev_sim_drain_events`] or to size a buffer defensively.
 *
 * Calling this does not mutate the sim — it drains the sim's queue
 * into the FFI buffer so the count is accurate, but no events are
 * dropped and a subsequent `ev_sim_drain_events` call returns the
 * same set.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_pending_event_count(struct EvSim *handle);

/**
 * Spawn a rider with default preferences.
 *
 * `origin` and `dest` are stop **entity** IDs (from
 * [`EvStopView::entity_id`]), not config-level `StopId` values.
 * `weight` is the rider's mass in the same units as
 * [`EvElevatorView::capacity_kg`].
 *
 * On success the new rider's entity id is written to `out_rider_id`.
 *
 * # Safety
 *
 * `handle` and `out_rider_id` must be valid pointers.
 */
enum EvStatus ev_sim_spawn_rider(struct EvSim *handle,
                                 uint64_t origin,
                                 uint64_t dest,
                                 double weight,
                                 uint64_t *out_rider_id);

/**
 * Spawn a rider with explicit preferences and patience.
 *
 * Like [`ev_sim_spawn_rider`] but allows setting boarding preferences
 * and a patience budget. Use sentinel values to skip optional fields:
 * - `abandon_after_ticks < 0`: no time-based abandonment
 * - `max_wait_ticks < 0`: no `Patience` component attached
 *
 * # Safety
 *
 * `handle` and `out_rider_id` must be valid pointers.
 */
enum EvStatus ev_sim_spawn_rider_ex(struct EvSim *handle,
                                    uint64_t origin,
                                    uint64_t dest,
                                    double weight,
                                    bool skip_full_elevator,
                                    double max_crowding_factor,
                                    int64_t abandon_after_ticks,
                                    bool abandon_on_full,
                                    int64_t max_wait_ticks,
                                    uint64_t *out_rider_id);

/**
 * Remove a rider from the simulation.
 *
 * The rider must be alive (any phase). Emits `RiderDespawned`
 * internally. Use this to clean up riders in terminal phases
 * (`Arrived`, `Abandoned`) and prevent unbounded memory growth.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_despawn_rider(struct EvSim *handle, uint64_t rider_entity_id);

/**
 * Add a new dispatch group. On success, writes the new group's id to
 * `*out_group_id`. Group ids are u32 and never reused.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_group_id` must be a
 * valid pointer to a writable u32.
 */
enum EvStatus ev_sim_add_group(struct EvSim *handle,
                               const char *name,
                               enum EvStrategy strategy,
                               uint32_t *out_group_id);

/**
 * Add a new line to an existing group. On success, writes the new line
 * entity id to `*out_line_entity_id`.
 *
 * `max_cars` is a sentinel: pass `0` for unlimited, otherwise the cap.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_line_entity_id` must
 * be a valid pointer to a writable u64.
 */
enum EvStatus ev_sim_add_line(struct EvSim *handle,
                              uint32_t group_id,
                              const char *name,
                              double min_position,
                              double max_position,
                              uint32_t max_cars,
                              uint64_t *out_line_entity_id);

/**
 * Add a new stop to a line. On success, writes the new stop entity id
 * to `*out_stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_stop_entity_id` must
 * be a valid pointer to a writable u64.
 */
enum EvStatus ev_sim_add_stop(struct EvSim *handle,
                              uint64_t line_entity_id,
                              const char *name,
                              double position,
                              uint64_t *out_stop_entity_id);

/**
 * Set the reachable position range of a line. Cars whose current
 * position falls outside the new `[min, max]` are clamped to the
 * boundary; their phase is left untouched.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_line_range(struct EvSim *handle,
                                    uint64_t line_entity_id,
                                    double min_position,
                                    double max_position);

/**
 * Remove a line. All elevators on the line are also removed; riders on
 * those elevators are ejected to the nearest remaining stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_line(struct EvSim *handle, uint64_t line_entity_id);

/**
 * Remove a stop. Riders waiting at this stop are abandoned; riders
 * destined here are rerouted to the next viable stop on their route.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_stop(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Populate `out_params` with the same defaults as
 * [`ElevatorParams::default()`](elevator_core::sim::ElevatorParams).
 *
 * `restricted_stops` is implicitly empty (callers pass `count = 0` to
 * [`ev_sim_add_elevator`]).
 *
 * # Safety
 *
 * `out_params` must be a writable [`EvElevatorParams`] pointer.
 */
enum EvStatus ev_sim_default_elevator_params(struct EvElevatorParams *out_params);

/**
 * Add a new elevator at runtime. On success, writes the new elevator
 * entity id to `*out_elevator_entity_id`.
 *
 * `restricted_stops` is a `(ptr, count)` pair giving the set of stop
 * entity ids this elevator cannot serve. Pass `(null, 0)` for no
 * restrictions. Duplicate entries are deduplicated.
 *
 * # Safety
 *
 * - `handle` must be a valid pointer returned by [`ev_sim_create`].
 * - `params` must be a valid pointer to a populated [`EvElevatorParams`].
 * - `restricted_stops` must point to at least `restricted_stops_count`
 *   contiguous `u64` values, or be null when `restricted_stops_count == 0`.
 * - `out_elevator_entity_id` must be a writable `u64` pointer.
 */
enum EvStatus ev_sim_add_elevator(struct EvSim *handle,
                                  const struct EvElevatorParams *params,
                                  const uint64_t *restricted_stops,
                                  uint32_t restricted_stops_count,
                                  uint64_t line_entity_id,
                                  double starting_position,
                                  uint64_t *out_elevator_entity_id);

/**
 * Remove an elevator. Riders aboard are ejected to the next scheduled
 * stop in the car's destination queue, or to the nearest stop on the
 * line if the queue is empty.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_elevator(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Add an existing stop to a line's served list.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_add_stop_to_line(struct EvSim *handle,
                                      uint64_t stop_entity_id,
                                      uint64_t line_entity_id);

/**
 * Remove a stop from a line's served list. The stop entity itself
 * remains in the world — call [`ev_sim_remove_stop`] to fully despawn.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_stop_from_line(struct EvSim *handle,
                                           uint64_t stop_entity_id,
                                           uint64_t line_entity_id);

/**
 * Reassign a line to a different group. Writes the previous group id
 * to `*out_old_group` on success.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_old_group` may be null if the caller does not need the previous id.
 */
enum EvStatus ev_sim_assign_line_to_group(struct EvSim *handle,
                                          uint64_t line_entity_id,
                                          uint32_t new_group,
                                          uint32_t *out_old_group);

/**
 * Reassign an elevator to a different line.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reassign_elevator_to_line(struct EvSim *handle,
                                               uint64_t elevator_entity_id,
                                               uint64_t new_line_entity_id);

/**
 * Set the list of stops `elevator_entity_id` is forbidden from
 * serving. The list replaces the current restriction set entirely.
 * Pass `count = 0` to clear all restrictions.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `stop_ids` must point to at least `count` `u64` values when
 * `count > 0`.
 */
enum EvStatus ev_sim_set_elevator_restricted_stops(struct EvSim *handle,
                                                   uint64_t elevator_entity_id,
                                                   const uint64_t *stop_ids,
                                                   uint32_t count);

/**
 * Pin `elevator_entity_id` to a hard-coded home stop. Whenever the
 * car is idle and off-position, the reposition phase routes it to
 * `home_stop_entity_id` regardless of the group's reposition strategy.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_elevator_home_stop(struct EvSim *handle,
                                            uint64_t elevator_entity_id,
                                            uint64_t home_stop_entity_id);

/**
 * Remove the home-stop pin from `elevator_entity_id`. Reposition
 * decisions return to the group's reposition strategy. Idempotent.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_clear_elevator_home_stop(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Read the home-stop pin for `elevator_entity_id`. Writes the stop
 * entity id (or `0` for unpinned) into `*out_stop_id` and returns
 * [`EvStatus::Ok`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_stop_id` must be a valid, writable pointer to a `u64`.
 */
enum EvStatus ev_sim_elevator_home_stop(struct EvSim *handle,
                                        uint64_t elevator_entity_id,
                                        uint64_t *out_stop_id);

/**
 * Attach `tag` to `entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `tag` must be a null-terminated UTF-8 C string.
 */
enum EvStatus ev_sim_tag_entity(struct EvSim *handle, uint64_t entity_id, const char *tag);

/**
 * Remove `tag` from `entity_id`. No-op if the entity wasn't tagged.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `tag` must be a null-terminated UTF-8 C string.
 */
enum EvStatus ev_sim_untag_entity(struct EvSim *handle, uint64_t entity_id, const char *tag);

/**
 * Replace a rider's destination with `new_destination_entity_id`. Used
 * for in-flight redirects (e.g. tenant changes mind).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reroute(struct EvSim *handle,
                             uint64_t rider_entity_id,
                             uint64_t new_destination_entity_id);

/**
 * Mark a rider as settled at their current stop (resident pool).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_settle_rider(struct EvSim *handle, uint64_t rider_entity_id);

/**
 * Attach an opaque tag to a rider. Stored verbatim — the engine never
 * interprets the value. Pass `0` to clear (the reserved "untagged"
 * sentinel). Survives snapshot round-trip.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_rider_tag(struct EvSim *handle, uint64_t rider_entity_id, uint64_t tag);

/**
 * Read the opaque tag attached to a rider. Writes the value into
 * `*out_tag` and returns [`EvStatus::Ok`]. Returns `0` for the default
 * "untagged" state.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_tag` must be a valid, writable pointer to a `u64`.
 */
enum EvStatus ev_sim_rider_tag(struct EvSim *handle, uint64_t rider_entity_id, uint64_t *out_tag);

/**
 * Replace a rider's remaining route with a single-leg route via
 * `group_id`. Convenience wrapper for the common "send this rider via
 * this group" case.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_rider_route_direct(struct EvSim *handle,
                                            uint64_t rider_entity_id,
                                            uint64_t from_stop_entity_id,
                                            uint64_t to_stop_entity_id,
                                            uint32_t group_id);

/**
 * Replace a rider's remaining route with a multi-leg route built from
 * `shortest_route(rider's current_stop → to_stop)`.
 *
 * Returns [`EvStatus::NotFound`] if no route exists or the rider has
 * no current stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_rider_route_shortest(struct EvSim *handle,
                                              uint64_t rider_entity_id,
                                              uint64_t to_stop_entity_id);

/**
 * Give a `Resident` rider a single-leg route via `group_id`,
 * transitioning them back to `Waiting`. The route's first leg origin
 * must match the rider's current stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reroute_rider_direct(struct EvSim *handle,
                                          uint64_t rider_entity_id,
                                          uint64_t from_stop_entity_id,
                                          uint64_t to_stop_entity_id,
                                          uint32_t group_id);

/**
 * Give a `Resident` rider a multi-leg route to `to_stop` built from
 * `shortest_route(rider's current_stop → to_stop)`, transitioning them
 * back to `Waiting`.
 *
 * Returns [`EvStatus::NotFound`] if the rider has no current stop or
 * no route exists.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reroute_rider_shortest(struct EvSim *handle,
                                            uint64_t rider_entity_id,
                                            uint64_t to_stop_entity_id);

/**
 * Replace a rider's allowed-stops set. Pass `count = 0` to clear.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `stop_ids` must point to at least `count` `u64` values when
 * `count > 0`.
 */
enum EvStatus ev_sim_set_rider_access(struct EvSim *handle,
                                      uint64_t rider_entity_id,
                                      const uint64_t *stop_ids,
                                      uint32_t count);

/**
 * Stops reachable from `from_stop_entity_id` via the line-graph.
 * Buffer-pattern accessor (see [`ev_sim_destination_queue`]).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reachable_stops_from(struct EvSim *handle,
                                          uint64_t from_stop_entity_id,
                                          uint64_t *out,
                                          uint32_t capacity,
                                          uint32_t *out_written);

/**
 * Stops where multiple lines intersect (transfer candidates).
 * Buffer-pattern accessor.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_transfer_points(struct EvSim *handle,
                                     uint64_t *out,
                                     uint32_t capacity,
                                     uint32_t *out_written);

/**
 * Resolve a config-time `StopId` (the small `u32` from RON config) to
 * its runtime `EntityId`. Returns `0` (slotmap-null) for unknown ids.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_stop_entity(struct EvSim *handle, uint32_t stop_id);

/**
 * Snapshot of the config-time `StopId` → runtime `EntityId` map.
 *
 * Buffer-pattern accessor; emits flat `[stop_id_as_u64, entity_id, ...]`
 * pairs (each pair = 2 `u64` slots). The number of pairs written is
 * `*out_written / 2`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_stop_lookup_iter(struct EvSim *handle,
                                      uint64_t *out,
                                      uint32_t capacity,
                                      uint32_t *out_written);

/**
 * Entity ids of every elevator currently repositioning.
 * Buffer-pattern accessor.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_iter_repositioning_elevators(struct EvSim *handle,
                                                  uint64_t *out,
                                                  uint32_t capacity,
                                                  uint32_t *out_written);

/**
 * Up/down split of riders waiting at a stop. Writes the up count to
 * `*out_up_count` and the down count to `*out_down_count`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_up_count` and `out_down_count` must be writable `u32` pointers.
 */
enum EvStatus ev_sim_waiting_direction_counts_at(struct EvSim *handle,
                                                 uint64_t stop_entity_id,
                                                 uint32_t *out_up_count,
                                                 uint32_t *out_down_count);

/**
 * Per-line waiting counts at a stop. Buffer-pattern accessor; emits
 * flat alternating `[line_entity_id, count, ...]` pairs as `u64`.
 * The number of pairs written is `*out_written / 2`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_waiting_counts_by_line_at(struct EvSim *handle,
                                               uint64_t stop_entity_id,
                                               uint64_t *out,
                                               uint32_t capacity,
                                               uint32_t *out_written);

/**
 * Entity ids of all elevators on `line_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_elevators_on_line(struct EvSim *handle,
                                       uint64_t line_entity_id,
                                       uint64_t *out,
                                       uint32_t capacity,
                                       uint32_t *out_written);

/**
 * Entity ids of every line in `group_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_lines_in_group(struct EvSim *handle,
                                    uint32_t group_id,
                                    uint64_t *out,
                                    uint32_t capacity,
                                    uint32_t *out_written);

/**
 * Entity ids of every line that serves `stop_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_lines_serving_stop(struct EvSim *handle,
                                        uint64_t stop_entity_id,
                                        uint64_t *out,
                                        uint32_t capacity,
                                        uint32_t *out_written);

/**
 * Entity ids of every stop served by `line_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_stops_served_by_line(struct EvSim *handle,
                                          uint64_t line_entity_id,
                                          uint64_t *out,
                                          uint32_t capacity,
                                          uint32_t *out_written);

/**
 * Group ids of every group with a line that serves `stop_entity_id`.
 * Returns a `u32` buffer (not `u64`) — `GroupId` is a u32 newtype.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u32` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_groups_serving_stop(struct EvSim *handle,
                                         uint64_t stop_entity_id,
                                         uint32_t *out,
                                         uint32_t capacity,
                                         uint32_t *out_written);

/**
 * Line entity that `elevator_entity_id` runs on. Returns `0`
 * (slotmap-null) for missing or non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_line_for_elevator(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Entity ids of every line in the simulation, across all groups.
 * Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_all_lines(struct EvSim *handle,
                               uint64_t *out,
                               uint32_t capacity,
                               uint32_t *out_written);

/**
 * Total number of lines across all groups.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_line_count(struct EvSim *handle);

/**
 * Find the stop entity at `position` on `line_entity_id`. Returns `0`
 * (slotmap-null) if no stop exists at that position on the line.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_find_stop_at_position_on_line(struct EvSim *handle,
                                              double position,
                                              uint64_t line_entity_id);

/**
 * Set the operational mode of an elevator.
 *
 * Modes are orthogonal to the elevator's phase — switching mode does not
 * teleport the car, but it changes how subsequent ticks treat it.
 * Leaving Manual zeroes velocity and clears any queued door commands.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_service_mode(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      enum EvServiceMode mode);

/**
 * Get the current operational mode of an elevator.
 *
 * Writes the mode to `*out_mode`. Returns `Normal` for missing/disabled
 * elevators (matches core's `service_mode` accessor, which returns the
 * default rather than erroring). Use [`ev_sim_frame`] to verify existence.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_mode` must be a valid pointer to a writable [`EvServiceMode`].
 */
enum EvStatus ev_sim_service_mode(struct EvSim *handle,
                                  uint64_t elevator_entity_id,
                                  enum EvServiceMode *out_mode);

/**
 * Set the target velocity for a Manual-mode elevator.
 *
 * Positive values command upward travel, negative values downward. The
 * car ramps toward the target each tick using its configured
 * acceleration / deceleration.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_target_velocity(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         double velocity);

/**
 * Command an immediate stop on a Manual-mode elevator.
 *
 * Sets the target velocity to zero; the car decelerates at its
 * configured rate. Emits a distinct event so games can distinguish an
 * emergency stop from a deliberate hold (`target_velocity` payload is
 * `None` in the event).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_emergency_stop(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Request the doors of an elevator to open.
 *
 * Applied immediately when the car is stopped at a stop with
 * closed/closing doors; otherwise queued until the car next arrives.
 * No-op if doors are already open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_open_door(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Request the doors to close now. Forces an early close unless a rider is
 * mid-boarding/exiting (in which case the close waits). If doors are
 * opening, the close queues until they reach fully-open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_close_door(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Extend the doors' open dwell by `ticks`. Cumulative — repeat calls add.
 * If doors aren't open yet, the hold queues and applies when they reach
 * fully-open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_hold_door(struct EvSim *handle, uint64_t elevator_entity_id, uint32_t ticks);

/**
 * Cancel any pending hold extension on the doors. If the base open timer
 * has already elapsed, the doors close on the next doors-phase tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_cancel_door_hold(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Set the maximum travel speed (distance/tick) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_max_speed(struct EvSim *handle,
                                   uint64_t elevator_entity_id,
                                   double max_speed);

/**
 * Set the acceleration rate (distance/tick²) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_acceleration(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      double acceleration);

/**
 * Set the deceleration rate (distance/tick²) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_deceleration(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      double deceleration);

/**
 * Set the weight capacity (kg) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_weight_capacity(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         double capacity);

/**
 * Set door transition (open/close) duration in ticks. Applied on the
 * next door cycle — an in-progress transition keeps its timing.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_door_transition_ticks(struct EvSim *handle,
                                               uint64_t elevator_entity_id,
                                               uint32_t ticks);

/**
 * Set how long doors hold fully open (ticks). Applied on the next door
 * cycle — a door currently dwelling completes its existing dwell first.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_door_open_ticks(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         uint32_t ticks);

/**
 * Set how many ticks the per-rider arrival log retains. Global setting
 * (not per-elevator). Higher = more memory but longer post-trip queries.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_arrival_log_retention_ticks(struct EvSim *handle,
                                                     uint64_t retention_ticks);

/**
 * Enable a previously-disabled entity (elevator or stop).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_enable(struct EvSim *handle, uint64_t entity_id);

/**
 * Disable an entity (elevator or stop). Disabled elevators eject riders
 * and are excluded from dispatch; disabled stops invalidate routes that
 * reference them.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_disable(struct EvSim *handle, uint64_t entity_id);

/**
 * Current velocity (distance/tick) of an elevator. Positive = up,
 * negative = down. Returns `NaN` for non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_velocity(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Sub-tick interpolated position of an entity. `alpha` in `[0.0, 1.0]`
 * (`0.0` = current tick, `1.0` = next tick). Returns `NaN` for entities
 * without a position component.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_position_at(struct EvSim *handle, uint64_t entity_id, double alpha);

/**
 * Fraction of capacity occupied by weight, in `[0.0, 1.0]`. Returns
 * `NaN` for non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_elevator_load(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Number of riders currently aboard. Returns `0` for empty cabs and
 * for non-elevator entities (disambiguate via [`ev_sim_is_elevator`]).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_occupancy(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Indicator-lamp direction of an elevator: `1` = Up, `-1` = Down,
 * `0` = Either / idle / missing entity. Encoding matches
 * [`EvHallCall::direction`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
int8_t ev_sim_elevator_direction(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Whether an elevator is currently committed upward. Returns `false`
 * for missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_elevator_going_up(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Whether an elevator is currently committed downward. Returns `false`
 * for missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_elevator_going_down(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Total number of completed trips since spawn. Returns `0` for missing
 * entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_elevator_move_count(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Distance the elevator would travel if it began decelerating now from
 * its current velocity. Returns `NaN` for stationary or missing
 * entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_braking_distance(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Position of the next stop in the destination queue (or current
 * target mid-trip). Returns `NaN` for empty queues / missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_future_stop_position(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Total number of currently-idle elevators across the simulation.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_idle_elevator_count(struct EvSim *handle);

/**
 * Whether an entity is an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_elevator(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is a rider.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_rider(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is a stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_stop(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is currently disabled. Returns `false` for both
 * "enabled" and "doesn't exist" — distinguish via the type-check
 * accessors first.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_disabled(struct EvSim *handle, uint64_t entity_id);

/**
 * Current simulation tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_current_tick(struct EvSim *handle);

/**
 * Time delta per tick (seconds). Useful for converting ETA tick counts
 * into real-time durations on the consumer side.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_dt(struct EvSim *handle);

/**
 * Append `stop_entity_id` to the back of `elevator_entity_id`'s
 * destination queue. Adjacent duplicates are suppressed.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_push_destination(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      uint64_t stop_entity_id);

/**
 * Insert `stop_entity_id` at the front of the destination queue
 * ("go here next").
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_push_destination_front(struct EvSim *handle,
                                            uint64_t elevator_entity_id,
                                            uint64_t stop_entity_id);

/**
 * Empty an elevator's destination queue. The in-flight trip continues
 * to its current target — call [`ev_sim_abort_movement`] to also stop
 * mid-flight.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_clear_destinations(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Abort the elevator's in-flight movement; decelerate to nearest stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_abort_movement(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Clear the queue and immediately recall to `stop_entity_id`. Emits a
 * distinct `ElevatorRecalled` event.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_recall_to(struct EvSim *handle,
                               uint64_t elevator_entity_id,
                               uint64_t stop_entity_id);

/**
 * Snapshot of an elevator's destination queue.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`. `out_written` must be a writable `u32`.
 */
enum EvStatus ev_sim_destination_queue(struct EvSim *handle,
                                       uint64_t elevator_entity_id,
                                       uint64_t *out,
                                       uint32_t capacity,
                                       uint32_t *out_written);

/**
 * Riders waiting at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_waiting_at(struct EvSim *handle,
                                uint64_t stop_entity_id,
                                uint64_t *out,
                                uint32_t capacity,
                                uint32_t *out_written);

/**
 * Number of riders waiting at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_waiting_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders settled / resident at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_residents_at(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  uint64_t *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of resident riders at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_resident_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders who abandoned the call at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_abandoned_at(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  uint64_t *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of abandoned riders at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_abandoned_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders currently aboard `elevator_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_riders_on(struct EvSim *handle,
                               uint64_t elevator_entity_id,
                               uint64_t *out,
                               uint32_t capacity,
                               uint32_t *out_written);

/**
 * Find the shortest multi-leg route between two stops using the
 * line-graph topology. On success writes the flattened stop sequence
 * (origin first, destination last) to `out_stops`.
 *
 * Caller-owned buffer pattern: `out_written` is populated with the
 * number of stops in the route regardless of buffer fit, so the caller
 * can probe with `(null, 0)` to size a real buffer.
 *
 * Returns:
 * - [`EvStatus::Ok`] if a route exists and fits in `capacity`.
 * - [`EvStatus::InvalidArg`] if the route exists but `capacity` is too
 *   small; `out_written` contains the required slot count.
 *   [`ev_last_error`] carries a diagnostic string only when
 *   `capacity > 0` — the documented `(null, 0)` probe is silent.
 * - [`EvStatus::NotFound`] if no route exists.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out_stops`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`. `out_written` must be a writable `u32`.
 */
enum EvStatus ev_sim_shortest_route(struct EvSim *handle,
                                    uint64_t from_stop_entity_id,
                                    uint64_t to_stop_entity_id,
                                    uint64_t *out_stops,
                                    uint32_t capacity,
                                    uint32_t *out_written);

/**
 * Number of active car calls inside `elevator_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_car_call_count(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Snapshot of car calls inside `elevator_entity_id`.
 *
 * Caller-owned buffer with probe-then-fill semantics: `out_written`
 * is populated with the **required** slot count regardless of whether
 * the buffer fits, so callers can probe with `(null, 0)` to size a
 * real buffer.
 *
 * Returns:
 * - [`EvStatus::Ok`] when all calls fit in `capacity` (`out_written
 *   <= capacity`); the first `out_written` slots of `out` are
 *   populated.
 * - [`EvStatus::InvalidArg`] when the buffer is too small;
 *   `out_written` carries the required slot count and no slot of
 *   `out` is written. [`ev_last_error`] carries a diagnostic string
 *   only when `capacity > 0` — the documented `(null, 0)` probe is
 *   silent.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable [`EvCarCall`] slots when
 * `capacity > 0`. `out_written` must be a writable `u32`.
 */
enum EvStatus ev_sim_car_calls_snapshot(struct EvSim *handle,
                                        uint64_t elevator_entity_id,
                                        struct EvCarCall *out,
                                        uint32_t capacity,
                                        uint32_t *out_written);

/**
 * Pending rider list for the `index`-th car call inside `elevator_entity_id`.
 * Caller-owned buffer pattern matching the call snapshot. Returns
 * [`EvStatus::NotFound`] if the index is out of range.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`. `out_written` must be a writable `u32`.
 */
enum EvStatus ev_sim_car_call_pending_riders(struct EvSim *handle,
                                             uint64_t elevator_entity_id,
                                             uint32_t index,
                                             uint64_t *out,
                                             uint32_t capacity,
                                             uint32_t *out_written);

/**
 * Read the full metrics snapshot.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_metrics` must be a writable [`EvMetrics`] pointer.
 */
enum EvStatus ev_sim_metrics(struct EvSim *handle, struct EvMetrics *out_metrics);

/**
 * Read the per-tag aggregates for `tag`. Returns [`EvStatus::NotFound`]
 * if no riders carrying the tag have been recorded yet.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `tag` must be a null-terminated UTF-8 C string. `out_metric` must be
 * a writable [`EvTaggedMetric`] pointer.
 */
enum EvStatus ev_sim_metrics_for_tag(struct EvSim *handle,
                                     const char *tag,
                                     struct EvTaggedMetric *out_metric);

/**
 * Number of registered metric tags.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_tag_count(struct EvSim *handle);

/**
 * List all registered metric tags.
 *
 * Caller-owned buffer pattern: `out` is an array of `*mut c_char` (one
 * slot per tag) backed by a flat scratch buffer of `scratch_capacity`
 * bytes; `out_written` receives the number of tags written,
 * `out_scratch_used` the number of bytes written to the scratch buffer
 * (including null terminators).
 *
 * Returns [`EvStatus::InvalidArg`] if either buffer is too small; the
 * `out_*` counts indicate the required sizes. [`ev_last_error`]
 * carries a diagnostic string only when at least one capacity is
 * non-zero — the documented `(null, 0, null, 0)` pure probe is
 * silent so callers reading [`ev_last_error`] after a deliberate
 * size query don't see a false "programmer mistake".
 *
 * # Safety
 *
 * `handle` must be valid. `out` and `scratch` may be null only when
 * their respective capacities are zero. `out_written` and
 * `out_scratch_used` must be writable `u32`s.
 */
enum EvStatus ev_sim_all_tags(struct EvSim *handle,
                              char **out,
                              uint32_t capacity,
                              char *scratch,
                              uint32_t scratch_capacity,
                              uint32_t *out_written,
                              uint32_t *out_scratch_used);

/**
 * Count elevators currently in `phase`.
 *
 * The `phase` argument uses the same encoding as [`EvElevatorView::phase`].
 * Only data-less variants are supported: `0` `Idle`, `3` `DoorOpening`,
 * `4` `Loading`, `5` `DoorClosing`, `6` `Stopped`.
 *
 * Returns [`EvStatus::InvalidArg`] for unknown phase codes.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_count` must be a writable `u32` pointer.
 */
enum EvStatus ev_sim_elevators_in_phase(struct EvSim *handle, uint8_t phase, uint32_t *out_count);

/**
 * ETA from `elevator_entity_id` to `stop_entity_id` in **ticks**.
 * Mirrors [`Simulation::eta`](elevator_core::sim::Simulation::eta).
 *
 * Returns [`EvStatus::InvalidArg`] if the entities don't refer to a
 * valid elevator/stop pair, or [`EvStatus::NotFound`] if the elevator
 * cannot reach the stop (e.g. stop not on the elevator's line, or
 * disabled).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_ticks` must be a writable `u64` pointer.
 */
enum EvStatus ev_sim_eta(struct EvSim *handle,
                         uint64_t elevator_entity_id,
                         uint64_t stop_entity_id,
                         uint64_t *out_ticks);

#endif  /* ELEVATOR_FFI_H */
