/* Auto-generated by cbindgen. Do not edit. */

#ifndef ELEVATOR_FFI_H
#define ELEVATOR_FFI_H

#pragma once

/* Generated. Do not modify by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Current ABI version. Bumped for any breaking change to the C layout.
 */
#define EV_ABI_VERSION 2

/**
 * `Event::HallButtonPressed`.
 */
#define HALL_BUTTON_PRESSED 1

/**
 * `Event::HallCallAcknowledged`.
 */
#define HALL_CALL_ACKNOWLEDGED 2

/**
 * `Event::HallCallCleared`.
 */
#define HALL_CALL_CLEARED 3

/**
 * `Event::CarButtonPressed`.
 */
#define CAR_BUTTON_PRESSED 4

/**
 * `Event::RiderSkipped`.
 */
#define RIDER_SKIPPED 5

/**
 * `Event::RiderSpawned`.
 */
#define RIDER_SPAWNED 6

/**
 * `Event::RiderBoarded`.
 */
#define RIDER_BOARDED 7

/**
 * `Event::RiderExited`.
 */
#define RIDER_EXITED 8

/**
 * `Event::RiderAbandoned`.
 */
#define RIDER_ABANDONED 9

/**
 * Status code returned by every FFI entrypoint.
 */
typedef enum EvStatus {
    /**
     * Operation succeeded.
     */
    Ok = 0,
    /**
     * A required pointer argument was null.
     */
    NullArg = 1,
    /**
     * A C string argument was not valid UTF-8.
     */
    InvalidUtf8 = 2,
    /**
     * The config file could not be read from disk.
     */
    ConfigLoad = 3,
    /**
     * The config file failed to parse as RON.
     */
    ConfigParse = 4,
    /**
     * [`SimulationBuilder::build`] returned an error.
     */
    BuildFailed = 5,
    /**
     * The requested entity, group, or resource was not found.
     */
    NotFound = 6,
    /**
     * An argument was structurally valid but semantically rejected.
     */
    InvalidArg = 7,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    Panic = 99,
} EvStatus;

/**
 * Built-in dispatch strategy identifier.
 */
typedef enum EvStrategy {
    /**
     * SCAN — sweep end-to-end.
     */
    Scan = 0,
    /**
     * LOOK — reverse at last request.
     */
    Look = 1,
    /**
     * Nearest-car.
     */
    NearestCar = 2,
    /**
     * Estimated time to destination.
     */
    Etd = 3,
} EvStrategy;

/**
 * Operational service mode for an elevator. Mirrors
 * [`elevator_core::components::ServiceMode`].
 */
typedef enum EvServiceMode {
    /**
     * Normal operation: dispatch assigns stops, doors auto-cycle.
     */
    Normal = 0,
    /**
     * Excluded from dispatch and repositioning. Consumer drives movement.
     */
    Independent = 1,
    /**
     * Reduced speed, doors hold open indefinitely.
     */
    Inspection = 2,
    /**
     * Driven by direct velocity commands. Doors follow manual API.
     */
    Manual = 3,
    /**
     * Shut down: excluded from dispatch, no auto-boarding, fully inert
     * once idle.
     */
    OutOfService = 4,
} EvServiceMode;

/**
 * Opaque simulation handle. Layout is not part of the ABI.
 */
typedef struct EvSim EvSim;

typedef struct Option_EvLogFn Option_EvLogFn;

/**
 * View of a single elevator at the current tick.
 */
typedef struct EvElevatorView {
    /**
     * Elevator entity id (raw slotmap `as_ffi()`).
     */
    uint64_t entity_id;
    /**
     * Group id this elevator belongs to (`u32::MAX` if orphaned).
     */
    uint32_t group_id;
    /**
     * Line (shaft/tether) entity id.
     */
    uint64_t line_id;
    /**
     * [`ElevatorPhase`] tag: 0 `Idle`, 1 `MovingToStop`, 2 `Repositioning`,
     * 3 `DoorOpening`, 4 `Loading`, 5 `DoorClosing`, 6 `Stopped`.
     */
    uint8_t phase;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Instantaneous velocity (+ up, - down).
     */
    double velocity;
    /**
     * Current stop (0 if not at a stop / moving).
     */
    uint64_t current_stop_id;
    /**
     * Target stop (0 if idle).
     */
    uint64_t target_stop_id;
    /**
     * Number of riders on board.
     */
    uint32_t occupancy;
    /**
     * Weight capacity in kg.
     */
    double capacity_kg;
    /**
     * [`DoorState`] tag: 0 `Closed`, 1 `Opening`, 2 `Open`, 3 `Closing`.
     */
    uint8_t door_state;
    /**
     * Direction indicator: 1 if the "going up" lamp is lit, 0 otherwise.
     */
    uint8_t going_up;
    /**
     * Direction indicator: 1 if the "going down" lamp is lit, 0 otherwise.
     */
    uint8_t going_down;
} EvElevatorView;

/**
 * View of a single stop at the current tick.
 */
typedef struct EvStopView {
    /**
     * Stop entity id.
     */
    uint64_t entity_id;
    /**
     * Config-level stop id (as declared in the RON file).
     */
    uint32_t stop_id;
    /**
     * Position along the shaft axis.
     */
    double position;
    /**
     * Number of riders currently waiting at this stop.
     */
    uint32_t waiting;
    /**
     * Number of resident (parked) riders at this stop.
     */
    uint32_t residents;
    /**
     * Number of riders who abandoned waiting at this stop.
     */
    uint32_t abandoned;
    /**
     * UTF-8 name bytes borrowed from the frame's arena.
     */
    const uint8_t *name_ptr;
    /**
     * Length in bytes of the name slice at [`Self::name_ptr`].
     */
    uintptr_t name_len;
} EvStopView;

/**
 * View of a single rider at the current tick.
 */
typedef struct EvRiderView {
    /**
     * Rider entity id.
     */
    uint64_t entity_id;
    /**
     * [`RiderPhase`] tag: 0 `Waiting`, 1 `Boarding`, 2 `Riding`, 3 `Exiting`,
     * 4 `Walking`, 5 `Arrived`, 6 `Abandoned`, 7 `Resident`.
     */
    uint8_t phase;
    /**
     * Origin / current stop entity id (0 if none).
     */
    uint64_t origin_stop_id;
    /**
     * Final destination stop entity id (0 if no route).
     */
    uint64_t destination_stop_id;
    /**
     * Elevator carrying the rider (0 if not aboard).
     */
    uint64_t elevator_id;
} EvRiderView;

/**
 * Aggregate metrics at the current tick.
 */
typedef struct EvMetricsView {
    /**
     * Cumulative riders delivered.
     */
    uint64_t total_delivered;
    /**
     * Cumulative riders who abandoned.
     */
    uint64_t total_abandoned;
    /**
     * Average wait time (seconds).
     */
    double avg_wait_seconds;
    /**
     * Average ride time (seconds).
     */
    double avg_ride_seconds;
    /**
     * Current simulation tick.
     */
    uint64_t current_tick;
} EvMetricsView;

/**
 * Borrowed per-tick snapshot. All slice pointers are valid until the next
 * call to [`ev_sim_frame`] on the same handle.
 */
typedef struct EvFrame {
    /**
     * Pointer to contiguous elevator views.
     */
    const struct EvElevatorView *elevators;
    /**
     * Number of elements at [`Self::elevators`].
     */
    uintptr_t elevator_count;
    /**
     * Pointer to contiguous stop views.
     */
    const struct EvStopView *stops;
    /**
     * Number of elements at [`Self::stops`].
     */
    uintptr_t stop_count;
    /**
     * Pointer to contiguous rider views.
     */
    const struct EvRiderView *riders;
    /**
     * Number of elements at [`Self::riders`].
     */
    uintptr_t rider_count;
    /**
     * Aggregate metrics snapshot.
     */
    struct EvMetricsView metrics;
} EvFrame;

/**
 * One `(line, car)` assignment on a hall call. Read by
 * [`ev_sim_assigned_cars_by_line`].
 */
typedef struct EvAssignment {
    /**
     * Line entity id the car runs on.
     */
    uint64_t line_entity_id;
    /**
     * Car entity id assigned to this line's share of the call.
     */
    uint64_t car_entity_id;
} EvAssignment;

/**
 * C-ABI-flat projection of a `HallCall` for FFI consumers.
 */
typedef struct EvHallCall {
    /**
     * Stop entity id (same encoding as elsewhere in the FFI).
     */
    uint64_t stop_entity_id;
    /**
     * `1` = Up, `-1` = Down.
     */
    int8_t direction;
    /**
     * Tick at which the button was pressed.
     */
    uint64_t press_tick;
    /**
     * Tick at which the call was acknowledged; `u64::MAX` if pending.
     */
    uint64_t acknowledged_at;
    /**
     * Car currently assigned to serve the call; `0` if none.
     *
     * At a stop served by multiple lines (e.g. a sky-lobby) a call can
     * hold one assignment per line. This field mirrors the FFI's
     * historical single-value shape and surfaces whichever entry has
     * the numerically smallest line-entity id. Use
     * [`ev_sim_assigned_cars_by_line`] to read every line's entry.
     */
    uint64_t assigned_car;
    /**
     * Destination stop entity id in DCS (`HallCallMode::Destination`)
     * mode, or `0` when the call has no destination (Classic mode,
     * or no kiosk entry yet). Matches `HallCall::destination`.
     */
    uint64_t destination_entity_id;
    /**
     * `1` when pinned, `0` otherwise.
     */
    uint8_t pinned;
    /**
     * Number of riders aggregated onto this call.
     */
    uint32_t pending_rider_count;
} EvHallCall;

/**
 * C-ABI-flat projection of the hall-call, car-call, skip, and rider
 * lifecycle events emitted by the simulation.
 *
 * All entity-id fields use `0` to mean "not applicable for this
 * event kind" (real entity ids are never zero under the FFI
 * encoding). The `kind` discriminator picks which fields are
 * meaningful — see [`ev_event_kind`] for the kind constants and the
 * [`ev_sim_drain_events`] docs for the per-kind field map.
 */
typedef struct EvEvent {
    /**
     * Event kind discriminator. Values outside [`ev_event_kind`] are
     * reserved — ignore unknown kinds for forward compatibility.
     */
    uint8_t kind;
    /**
     * Direction for hall-call events: `1` = Up, `-1` = Down, `0` = N/A.
     */
    int8_t direction;
    /**
     * Tick the event was emitted on.
     */
    uint64_t tick;
    /**
     * Stop entity id. Used by hall-call events, `RiderSkipped`,
     * `RiderSpawned` (origin), `RiderExited`, `RiderAbandoned`.
     * `0` when not applicable.
     */
    uint64_t stop;
    /**
     * Car/elevator entity id. Used by `HallCallCleared`,
     * `CarButtonPressed`, `RiderSkipped`, `RiderBoarded`,
     * `RiderExited`. `0` when not applicable.
     */
    uint64_t car;
    /**
     * Rider entity id. Used by `CarButtonPressed`, `RiderSkipped`,
     * and all rider lifecycle events. `0` when not applicable.
     */
    uint64_t rider;
    /**
     * Destination stop entity id. Used by `CarButtonPressed` (the
     * requested floor) and `RiderSpawned` (the rider's destination).
     * `0` for all other kinds.
     */
    uint64_t floor;
} EvEvent;

/**
 * Return the ABI version compiled into this shared library.
 */
uint32_t ev_abi_version(void);

/**
 * Return a pointer to a null-terminated description of the last error on
 * this thread, or null if no error has been recorded.
 *
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *ev_last_error(void);

/**
 * Install (or clear, by passing null) a global log callback.
 *
 * All subsequent [`ev_sim_step`] calls drain `sim.pending_events()` and
 * forward a debug-formatted message per event.
 *
 * # Safety
 *
 * The caller guarantees that, while the callback remains installed, the
 * function pointer is valid to invoke.
 */
void ev_set_log_callback(struct Option_EvLogFn cb);

/**
 * Create a new simulation from a RON config on disk.
 *
 * Returns a newly allocated handle on success, or null on failure — call
 * [`ev_last_error`] for details.
 *
 * # Safety
 *
 * `config_path` must be a null-terminated UTF-8 C string, or null.
 */
struct EvSim *ev_sim_create(const char *config_path);

/**
 * Destroy a simulation handle. Null-safe.
 *
 * # Safety
 *
 * `handle` must either be null or a pointer returned by [`ev_sim_create`]
 * that has not already been destroyed.
 */
void ev_sim_destroy(struct EvSim *handle);

/**
 * Advance the simulation by one tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_step(struct EvSim *handle);

/**
 * Populate `out` with a borrowed view of the current simulation state.
 *
 * Pointers inside the frame are valid until the next `ev_sim_frame` call
 * on the same handle.
 *
 * # Safety
 *
 * `handle` and `out` must be valid, aligned, non-overlapping pointers.
 */
enum EvStatus ev_sim_frame(struct EvSim *handle, struct EvFrame *out);

/**
 * Query the best ETA to a stop across eligible elevators.
 *
 * `direction`: `-1` = Down, `0` = Either, `1` = Up. Returns
 * [`EvStatus::NotFound`] if no eligible elevator has `stop_entity_id`
 * queued; in that case the out-parameters are written as `(0, NaN)`.
 *
 * # Safety
 *
 * All pointers must be valid, aligned, and non-null.
 */
enum EvStatus ev_sim_best_eta(struct EvSim *handle,
                              uint64_t stop_entity_id,
                              int8_t direction,
                              uint64_t *out_elevator,
                              double *out_seconds);

/**
 * Replace the dispatch strategy for a group.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_strategy(struct EvSim *handle,
                                  uint32_t group_id,
                                  enum EvStrategy strategy);

/**
 * Remove the reposition strategy from `group_id`. Idle elevators stay
 * where they parked instead of moving toward a target.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_reposition(struct EvSim *handle, uint32_t group_id);

/**
 * Step the simulation forward up to `max_ticks` ticks.
 *
 * Stops early if the world becomes "quiet" (no in-flight riders, no
 * pending hall calls, all cars idle). Writes the actual tick count
 * to `*out_ticks_run` on both success and timeout.
 *
 * Returns `EvStatus::Ok` if the world quieted within `max_ticks`,
 * `EvStatus::InvalidArg` if it failed to quiet (loop guard).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_ticks_run` must be a writable `u64`.
 */
enum EvStatus ev_sim_run_until_quiet(struct EvSim *handle,
                                     uint64_t max_ticks,
                                     uint64_t *out_ticks_run);

/**
 * Press an up/down hall button at `stop_entity_id`. Games use this
 * for scripted NPCs, player input, or cutscene cues.
 *
 * `direction` uses `1` = Up, `-1` = Down.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_hall_button(struct EvSim *handle,
                                       uint64_t stop_entity_id,
                                       int8_t direction);

/**
 * Press a floor button inside a car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_press_car_button(struct EvSim *handle,
                                      uint64_t car_entity_id,
                                      uint64_t floor_entity_id);

/**
 * Pin the hall call at `(stop, direction)` to a specific car.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_pin_assignment(struct EvSim *handle,
                                    uint64_t car_entity_id,
                                    uint64_t stop_entity_id,
                                    int8_t direction);

/**
 * Release a previous pin at `(stop, direction)`. No-op if none.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_unpin_assignment(struct EvSim *handle,
                                      uint64_t stop_entity_id,
                                      int8_t direction);

/**
 * Car currently assigned to serve the hall call at `(stop, direction)`.
 *
 * Writes the car's entity id to `out_elevator`, or `0` if no call
 * exists or no car is assigned.
 *
 * # Safety
 *
 * `handle` and `out_elevator` must be valid pointers.
 */
enum EvStatus ev_sim_assigned_car(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_elevator);

/**
 * Per-line car assignments at the hall call `(stop, direction)`.
 *
 * Writes up to `capacity` [`EvAssignment`] records to `out` and the
 * number actually written to `out_written`. Lines with no assignment
 * are omitted. Iteration order follows the `BTreeMap` keyed by line
 * entity id — stable across ticks.
 *
 * Use [`ev_sim_assigned_car`] for the single-value convenience view;
 * this call is for consumers that need every line's assignment at a
 * multi-line stop (e.g. a sky-lobby served by low, high, and express
 * banks).
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvAssignment`]s.
 */
enum EvStatus ev_sim_assigned_cars_by_line(struct EvSim *handle,
                                           uint64_t stop_entity_id,
                                           int8_t direction,
                                           struct EvAssignment *out,
                                           uint32_t capacity,
                                           uint32_t *out_written);

/**
 * Estimated ticks remaining before the assigned car reaches the call.
 *
 * Writes the tick count to `out_ticks`, or `u64::MAX` when no car is
 * assigned or no call exists at that `(stop, direction)`.
 *
 * # Safety
 *
 * `handle` and `out_ticks` must be valid pointers.
 */
enum EvStatus ev_sim_eta_for_call(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  int8_t direction,
                                  uint64_t *out_ticks);

/**
 * Number of active hall calls across the whole simulation. Use as a
 * pre-check before allocating a buffer for
 * [`ev_sim_hall_calls_snapshot`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_hall_call_count(struct EvSim *handle);

/**
 * Snapshot a flat representation of every active hall call into `out`.
 *
 * The caller supplies a buffer of `capacity` [`EvHallCall`] entries;
 * the actual number written is returned in `out_written`. If
 * `capacity` is smaller than the live count, the buffer is filled
 * and the remainder is dropped.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` `EvHallCall`s.
 */
enum EvStatus ev_sim_hall_calls_snapshot(struct EvSim *handle,
                                         struct EvHallCall *out,
                                         uint32_t capacity,
                                         uint32_t *out_written);

/**
 * Drain pending events into `out`.
 *
 * Delivers hall-call, car-call, skip, and rider lifecycle events.
 * Every event produced by the simulation is eventually delivered
 * exactly once, then removed from the internal queue. Call after
 * `ev_sim_step` each tick to catch new events.
 *
 * Field meanings by [`EvEvent::kind`]:
 * - `HALL_BUTTON_PRESSED` / `HALL_CALL_ACKNOWLEDGED`: `stop`,
 *   `direction`, `tick`.
 * - `HALL_CALL_CLEARED`: `stop`, `direction`, `car`, `tick`.
 * - `CAR_BUTTON_PRESSED`: `car`, `floor`, `rider` (or `0` for
 *   synthetic presses), `tick`.
 * - `RIDER_SKIPPED`: `rider`, `car` (elevator), `stop`, `tick`.
 * - `RIDER_SPAWNED`: `rider`, `stop` (origin), `floor`
 *   (destination), `tick`.
 * - `RIDER_BOARDED`: `rider`, `car` (elevator), `tick`.
 * - `RIDER_EXITED`: `rider`, `car` (elevator), `stop`, `tick`.
 * - `RIDER_ABANDONED`: `rider`, `stop`, `tick`.
 *
 * Unused fields for each kind are zeroed so the caller can inspect
 * a uniform struct layout. Other event kinds in the sim (door
 * transitions, direction indicators, etc.) are not surfaced.
 * Future kinds extend the discriminator.
 *
 * ## Overflow handling — no silent drops
 *
 * If more than `capacity` events are pending, the first `capacity`
 * are written and the rest stay in an internal queue for the next
 * call. Callers can detect a truncated read two ways:
 * - `out_written == capacity` is *possibly* truncated. Call
 *   [`ev_sim_pending_event_count`] afterward; non-zero means more
 *   are queued.
 * - Drain in a loop until `ev_sim_pending_event_count` returns `0`.
 *
 * # Safety
 *
 * `handle`, `out`, and `out_written` must be valid pointers. `out`
 * must point to a buffer of at least `capacity` [`EvEvent`]s.
 */
enum EvStatus ev_sim_drain_events(struct EvSim *handle,
                                  struct EvEvent *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of events parked in the FFI event buffer plus any pending
 * in the underlying simulation queue. Use this to detect truncation
 * after [`ev_sim_drain_events`] or to size a buffer defensively.
 *
 * Calling this does not mutate the sim — it drains the sim's queue
 * into the FFI buffer so the count is accurate, but no events are
 * dropped and a subsequent `ev_sim_drain_events` call returns the
 * same set.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_pending_event_count(struct EvSim *handle);

/**
 * Spawn a rider with default preferences.
 *
 * `origin` and `dest` are stop **entity** IDs (from
 * [`EvStopView::entity_id`]), not config-level `StopId` values.
 * `weight` is the rider's mass in the same units as
 * [`EvElevatorView::capacity_kg`].
 *
 * On success the new rider's entity id is written to `out_rider_id`.
 *
 * # Safety
 *
 * `handle` and `out_rider_id` must be valid pointers.
 */
enum EvStatus ev_sim_spawn_rider(struct EvSim *handle,
                                 uint64_t origin,
                                 uint64_t dest,
                                 double weight,
                                 uint64_t *out_rider_id);

/**
 * Spawn a rider with explicit preferences and patience.
 *
 * Like [`ev_sim_spawn_rider`] but allows setting boarding preferences
 * and a patience budget. Use sentinel values to skip optional fields:
 * - `abandon_after_ticks < 0`: no time-based abandonment
 * - `max_wait_ticks < 0`: no `Patience` component attached
 *
 * # Safety
 *
 * `handle` and `out_rider_id` must be valid pointers.
 */
enum EvStatus ev_sim_spawn_rider_ex(struct EvSim *handle,
                                    uint64_t origin,
                                    uint64_t dest,
                                    double weight,
                                    bool skip_full_elevator,
                                    double max_crowding_factor,
                                    int64_t abandon_after_ticks,
                                    bool abandon_on_full,
                                    int64_t max_wait_ticks,
                                    uint64_t *out_rider_id);

/**
 * Remove a rider from the simulation.
 *
 * The rider must be alive (any phase). Emits `RiderDespawned`
 * internally. Use this to clean up riders in terminal phases
 * (`Arrived`, `Abandoned`) and prevent unbounded memory growth.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_despawn_rider(struct EvSim *handle, uint64_t rider_entity_id);

/**
 * Add a new dispatch group. On success, writes the new group's id to
 * `*out_group_id`. Group ids are u32 and never reused.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_group_id` must be a
 * valid pointer to a writable u32.
 */
enum EvStatus ev_sim_add_group(struct EvSim *handle,
                               const char *name,
                               enum EvStrategy strategy,
                               uint32_t *out_group_id);

/**
 * Add a new line to an existing group. On success, writes the new line
 * entity id to `*out_line_entity_id`.
 *
 * `max_cars` is a sentinel: pass `0` for unlimited, otherwise the cap.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_line_entity_id` must
 * be a valid pointer to a writable u64.
 */
enum EvStatus ev_sim_add_line(struct EvSim *handle,
                              uint32_t group_id,
                              const char *name,
                              double min_position,
                              double max_position,
                              uint32_t max_cars,
                              uint64_t *out_line_entity_id);

/**
 * Add a new stop to a line. On success, writes the new stop entity id
 * to `*out_stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `name`
 * must be a null-terminated UTF-8 C string. `out_stop_entity_id` must
 * be a valid pointer to a writable u64.
 */
enum EvStatus ev_sim_add_stop(struct EvSim *handle,
                              uint64_t line_entity_id,
                              const char *name,
                              double position,
                              uint64_t *out_stop_entity_id);

/**
 * Set the reachable position range of a line. Cars whose current
 * position falls outside the new `[min, max]` are clamped to the
 * boundary; their phase is left untouched.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_line_range(struct EvSim *handle,
                                    uint64_t line_entity_id,
                                    double min_position,
                                    double max_position);

/**
 * Remove a line. All elevators on the line are also removed; riders on
 * those elevators are ejected to the nearest remaining stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_line(struct EvSim *handle, uint64_t line_entity_id);

/**
 * Remove a stop. Riders waiting at this stop are abandoned; riders
 * destined here are rerouted to the next viable stop on their route.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_stop(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Remove an elevator. Riders aboard are ejected to the next scheduled
 * stop in the car's destination queue, or to the nearest stop on the
 * line if the queue is empty.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_elevator(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Add an existing stop to a line's served list.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_add_stop_to_line(struct EvSim *handle,
                                      uint64_t stop_entity_id,
                                      uint64_t line_entity_id);

/**
 * Remove a stop from a line's served list. The stop entity itself
 * remains in the world — call [`ev_sim_remove_stop`] to fully despawn.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_remove_stop_from_line(struct EvSim *handle,
                                           uint64_t stop_entity_id,
                                           uint64_t line_entity_id);

/**
 * Reassign a line to a different group. Writes the previous group id
 * to `*out_old_group` on success.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_old_group` may be null if the caller does not need the previous id.
 */
enum EvStatus ev_sim_assign_line_to_group(struct EvSim *handle,
                                          uint64_t line_entity_id,
                                          uint32_t new_group,
                                          uint32_t *out_old_group);

/**
 * Reassign an elevator to a different line.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reassign_elevator_to_line(struct EvSim *handle,
                                               uint64_t elevator_entity_id,
                                               uint64_t new_line_entity_id);

/**
 * Set the list of stops `elevator_entity_id` is forbidden from
 * serving. The list replaces the current restriction set entirely.
 * Pass `count = 0` to clear all restrictions.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `stop_ids` must point to at least `count` `u64` values when
 * `count > 0`.
 */
enum EvStatus ev_sim_set_elevator_restricted_stops(struct EvSim *handle,
                                                   uint64_t elevator_entity_id,
                                                   const uint64_t *stop_ids,
                                                   uint32_t count);

/**
 * Attach `tag` to `entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `tag` must be a null-terminated UTF-8 C string.
 */
enum EvStatus ev_sim_tag_entity(struct EvSim *handle, uint64_t entity_id, const char *tag);

/**
 * Remove `tag` from `entity_id`. No-op if the entity wasn't tagged.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `tag` must be a null-terminated UTF-8 C string.
 */
enum EvStatus ev_sim_untag_entity(struct EvSim *handle, uint64_t entity_id, const char *tag);

/**
 * Replace a rider's destination with `new_destination_entity_id`. Used
 * for in-flight redirects (e.g. tenant changes mind).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reroute(struct EvSim *handle,
                             uint64_t rider_entity_id,
                             uint64_t new_destination_entity_id);

/**
 * Mark a rider as settled at their current stop (resident pool).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_settle_rider(struct EvSim *handle, uint64_t rider_entity_id);

/**
 * Replace a rider's allowed-stops set. Pass `count = 0` to clear.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `stop_ids` must point to at least `count` `u64` values when
 * `count > 0`.
 */
enum EvStatus ev_sim_set_rider_access(struct EvSim *handle,
                                      uint64_t rider_entity_id,
                                      const uint64_t *stop_ids,
                                      uint32_t count);

/**
 * Stops reachable from `from_stop_entity_id` via the line-graph.
 * Buffer-pattern accessor (see [`ev_sim_destination_queue`]).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_reachable_stops_from(struct EvSim *handle,
                                          uint64_t from_stop_entity_id,
                                          uint64_t *out,
                                          uint32_t capacity,
                                          uint32_t *out_written);

/**
 * Stops where multiple lines intersect (transfer candidates).
 * Buffer-pattern accessor.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_transfer_points(struct EvSim *handle,
                                     uint64_t *out,
                                     uint32_t capacity,
                                     uint32_t *out_written);

/**
 * Resolve a config-time `StopId` (the small `u32` from RON config) to
 * its runtime `EntityId`. Returns `0` (slotmap-null) for unknown ids.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_stop_entity(struct EvSim *handle, uint32_t stop_id);

/**
 * Snapshot of the config-time `StopId` → runtime `EntityId` map.
 *
 * Buffer-pattern accessor; emits flat `[stop_id_as_u64, entity_id, ...]`
 * pairs (each pair = 2 `u64` slots). The number of pairs written is
 * `*out_written / 2`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_stop_lookup_iter(struct EvSim *handle,
                                      uint64_t *out,
                                      uint32_t capacity,
                                      uint32_t *out_written);

/**
 * Entity ids of every elevator currently repositioning.
 * Buffer-pattern accessor.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_iter_repositioning_elevators(struct EvSim *handle,
                                                  uint64_t *out,
                                                  uint32_t capacity,
                                                  uint32_t *out_written);

/**
 * Up/down split of riders waiting at a stop. Writes the up count to
 * `*out_up_count` and the down count to `*out_down_count`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_up_count` and `out_down_count` must be writable `u32` pointers.
 */
enum EvStatus ev_sim_waiting_direction_counts_at(struct EvSim *handle,
                                                 uint64_t stop_entity_id,
                                                 uint32_t *out_up_count,
                                                 uint32_t *out_down_count);

/**
 * Per-line waiting counts at a stop. Buffer-pattern accessor; emits
 * flat alternating `[line_entity_id, count, ...]` pairs as `u64`.
 * The number of pairs written is `*out_written / 2`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_waiting_counts_by_line_at(struct EvSim *handle,
                                               uint64_t stop_entity_id,
                                               uint64_t *out,
                                               uint32_t capacity,
                                               uint32_t *out_written);

/**
 * Entity ids of all elevators on `line_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_elevators_on_line(struct EvSim *handle,
                                       uint64_t line_entity_id,
                                       uint64_t *out,
                                       uint32_t capacity,
                                       uint32_t *out_written);

/**
 * Entity ids of every line in `group_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_lines_in_group(struct EvSim *handle,
                                    uint32_t group_id,
                                    uint64_t *out,
                                    uint32_t capacity,
                                    uint32_t *out_written);

/**
 * Entity ids of every line that serves `stop_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_lines_serving_stop(struct EvSim *handle,
                                        uint64_t stop_entity_id,
                                        uint64_t *out,
                                        uint32_t capacity,
                                        uint32_t *out_written);

/**
 * Entity ids of every stop served by `line_entity_id`. Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_stops_served_by_line(struct EvSim *handle,
                                          uint64_t line_entity_id,
                                          uint64_t *out,
                                          uint32_t capacity,
                                          uint32_t *out_written);

/**
 * Group ids of every group with a line that serves `stop_entity_id`.
 * Returns a `u32` buffer (not `u64`) — `GroupId` is a u32 newtype.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u32` slots when
 * `capacity > 0`.
 */
enum EvStatus ev_sim_groups_serving_stop(struct EvSim *handle,
                                         uint64_t stop_entity_id,
                                         uint32_t *out,
                                         uint32_t capacity,
                                         uint32_t *out_written);

/**
 * Line entity that `elevator_entity_id` runs on. Returns `0`
 * (slotmap-null) for missing or non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_line_for_elevator(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Entity ids of every line in the simulation, across all groups.
 * Buffer-pattern.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_all_lines(struct EvSim *handle,
                               uint64_t *out,
                               uint32_t capacity,
                               uint32_t *out_written);

/**
 * Total number of lines across all groups.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_line_count(struct EvSim *handle);

/**
 * Find the stop entity at `position` on `line_entity_id`. Returns `0`
 * (slotmap-null) if no stop exists at that position on the line.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_find_stop_at_position_on_line(struct EvSim *handle,
                                              double position,
                                              uint64_t line_entity_id);

/**
 * Set the operational mode of an elevator.
 *
 * Modes are orthogonal to the elevator's phase — switching mode does not
 * teleport the car, but it changes how subsequent ticks treat it.
 * Leaving Manual zeroes velocity and clears any queued door commands.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_service_mode(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      enum EvServiceMode mode);

/**
 * Get the current operational mode of an elevator.
 *
 * Writes the mode to `*out_mode`. Returns `Normal` for missing/disabled
 * elevators (matches core's `service_mode` accessor, which returns the
 * default rather than erroring). Use [`ev_sim_frame`] to verify existence.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 * `out_mode` must be a valid pointer to a writable [`EvServiceMode`].
 */
enum EvStatus ev_sim_service_mode(struct EvSim *handle,
                                  uint64_t elevator_entity_id,
                                  enum EvServiceMode *out_mode);

/**
 * Set the target velocity for a Manual-mode elevator.
 *
 * Positive values command upward travel, negative values downward. The
 * car ramps toward the target each tick using its configured
 * acceleration / deceleration.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_target_velocity(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         double velocity);

/**
 * Command an immediate stop on a Manual-mode elevator.
 *
 * Sets the target velocity to zero; the car decelerates at its
 * configured rate. Emits a distinct event so games can distinguish an
 * emergency stop from a deliberate hold (`target_velocity` payload is
 * `None` in the event).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_emergency_stop(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Request the doors of an elevator to open.
 *
 * Applied immediately when the car is stopped at a stop with
 * closed/closing doors; otherwise queued until the car next arrives.
 * No-op if doors are already open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_open_door(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Request the doors to close now. Forces an early close unless a rider is
 * mid-boarding/exiting (in which case the close waits). If doors are
 * opening, the close queues until they reach fully-open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_close_door(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Extend the doors' open dwell by `ticks`. Cumulative — repeat calls add.
 * If doors aren't open yet, the hold queues and applies when they reach
 * fully-open.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_hold_door(struct EvSim *handle, uint64_t elevator_entity_id, uint32_t ticks);

/**
 * Cancel any pending hold extension on the doors. If the base open timer
 * has already elapsed, the doors close on the next doors-phase tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_cancel_door_hold(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Set the maximum travel speed (distance/tick) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_max_speed(struct EvSim *handle,
                                   uint64_t elevator_entity_id,
                                   double max_speed);

/**
 * Set the acceleration rate (distance/tick²) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_acceleration(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      double acceleration);

/**
 * Set the deceleration rate (distance/tick²) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_deceleration(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      double deceleration);

/**
 * Set the weight capacity (kg) of an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_weight_capacity(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         double capacity);

/**
 * Set door transition (open/close) duration in ticks. Applied on the
 * next door cycle — an in-progress transition keeps its timing.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_door_transition_ticks(struct EvSim *handle,
                                               uint64_t elevator_entity_id,
                                               uint32_t ticks);

/**
 * Set how long doors hold fully open (ticks). Applied on the next door
 * cycle — a door currently dwelling completes its existing dwell first.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_door_open_ticks(struct EvSim *handle,
                                         uint64_t elevator_entity_id,
                                         uint32_t ticks);

/**
 * Set how many ticks the per-rider arrival log retains. Global setting
 * (not per-elevator). Higher = more memory but longer post-trip queries.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_set_arrival_log_retention_ticks(struct EvSim *handle,
                                                     uint64_t retention_ticks);

/**
 * Enable a previously-disabled entity (elevator or stop).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_enable(struct EvSim *handle, uint64_t entity_id);

/**
 * Disable an entity (elevator or stop). Disabled elevators eject riders
 * and are excluded from dispatch; disabled stops invalidate routes that
 * reference them.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_disable(struct EvSim *handle, uint64_t entity_id);

/**
 * Current velocity (distance/tick) of an elevator. Positive = up,
 * negative = down. Returns `NaN` for non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_velocity(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Sub-tick interpolated position of an entity. `alpha` in `[0.0, 1.0]`
 * (`0.0` = current tick, `1.0` = next tick). Returns `NaN` for entities
 * without a position component.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_position_at(struct EvSim *handle, uint64_t entity_id, double alpha);

/**
 * Fraction of capacity occupied by weight, in `[0.0, 1.0]`. Returns
 * `NaN` for non-elevator entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_elevator_load(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Number of riders currently aboard. Returns `0` for empty cabs and
 * for non-elevator entities (disambiguate via [`ev_sim_is_elevator`]).
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_occupancy(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Indicator-lamp direction of an elevator: `1` = Up, `-1` = Down,
 * `0` = Either / idle / missing entity. Encoding matches
 * [`EvHallCall::direction`].
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
int8_t ev_sim_elevator_direction(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Whether an elevator is currently committed upward. Returns `false`
 * for missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_elevator_going_up(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Whether an elevator is currently committed downward. Returns `false`
 * for missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_elevator_going_down(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Total number of completed trips since spawn. Returns `0` for missing
 * entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_elevator_move_count(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Distance the elevator would travel if it began decelerating now from
 * its current velocity. Returns `NaN` for stationary or missing
 * entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_braking_distance(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Position of the next stop in the destination queue (or current
 * target mid-trip). Returns `NaN` for empty queues / missing entities.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_future_stop_position(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Total number of currently-idle elevators across the simulation.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_idle_elevator_count(struct EvSim *handle);

/**
 * Whether an entity is an elevator.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_elevator(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is a rider.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_rider(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is a stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_stop(struct EvSim *handle, uint64_t entity_id);

/**
 * Whether an entity is currently disabled. Returns `false` for both
 * "enabled" and "doesn't exist" — distinguish via the type-check
 * accessors first.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
bool ev_sim_is_disabled(struct EvSim *handle, uint64_t entity_id);

/**
 * Current simulation tick.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint64_t ev_sim_current_tick(struct EvSim *handle);

/**
 * Time delta per tick (seconds). Useful for converting ETA tick counts
 * into real-time durations on the consumer side.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
double ev_sim_dt(struct EvSim *handle);

/**
 * Append `stop_entity_id` to the back of `elevator_entity_id`'s
 * destination queue. Adjacent duplicates are suppressed.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_push_destination(struct EvSim *handle,
                                      uint64_t elevator_entity_id,
                                      uint64_t stop_entity_id);

/**
 * Insert `stop_entity_id` at the front of the destination queue
 * ("go here next").
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_push_destination_front(struct EvSim *handle,
                                            uint64_t elevator_entity_id,
                                            uint64_t stop_entity_id);

/**
 * Empty an elevator's destination queue. The in-flight trip continues
 * to its current target — call [`ev_sim_abort_movement`] to also stop
 * mid-flight.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_clear_destinations(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Abort the elevator's in-flight movement; decelerate to nearest stop.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_abort_movement(struct EvSim *handle, uint64_t elevator_entity_id);

/**
 * Clear the queue and immediately recall to `stop_entity_id`. Emits a
 * distinct `ElevatorRecalled` event.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
enum EvStatus ev_sim_recall_to(struct EvSim *handle,
                               uint64_t elevator_entity_id,
                               uint64_t stop_entity_id);

/**
 * Snapshot of an elevator's destination queue.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`]. `out`
 * must point to at least `capacity` writable `u64` slots when
 * `capacity > 0`. `out_written` must be a writable `u32`.
 */
enum EvStatus ev_sim_destination_queue(struct EvSim *handle,
                                       uint64_t elevator_entity_id,
                                       uint64_t *out,
                                       uint32_t capacity,
                                       uint32_t *out_written);

/**
 * Riders waiting at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_waiting_at(struct EvSim *handle,
                                uint64_t stop_entity_id,
                                uint64_t *out,
                                uint32_t capacity,
                                uint32_t *out_written);

/**
 * Number of riders waiting at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_waiting_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders settled / resident at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_residents_at(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  uint64_t *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of resident riders at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_resident_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders who abandoned the call at `stop_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_abandoned_at(struct EvSim *handle,
                                  uint64_t stop_entity_id,
                                  uint64_t *out,
                                  uint32_t capacity,
                                  uint32_t *out_written);

/**
 * Number of abandoned riders at `stop_entity_id`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`ev_sim_create`].
 */
uint32_t ev_sim_abandoned_count_at(struct EvSim *handle, uint64_t stop_entity_id);

/**
 * Riders currently aboard `elevator_entity_id`.
 *
 * # Safety
 *
 * See [`ev_sim_destination_queue`] for buffer requirements.
 */
enum EvStatus ev_sim_riders_on(struct EvSim *handle,
                               uint64_t elevator_entity_id,
                               uint64_t *out,
                               uint32_t capacity,
                               uint32_t *out_written);

#endif  /* ELEVATOR_FFI_H */
