//! GameMaker Studio 2 return-register bridge.
//!
//! For every public `ev_*` function whose native return type is an
//! integer, enum, `bool`, or pointer, this module exports a companion
//! `<name>_gms` symbol that forwards the arguments unchanged and
//! bit-reinterprets the underlying return value as the same-width
//! `f64` pattern.
//!
//! ## Why this exists (issue #876)
//!
//! GameMaker's `external_define` / `external_call` is restricted to
//! two return forms: `ty_real` (an IEEE-754 double, read from the
//! float return register `xmm0` on x64 / `d0` on AAPCS / arm64) and
//! `ty_string` (a UTF-8 `char *`, picked up via the integer return
//! register). For functions whose Rust signature declares an integer
//! return — say `pub extern "C" fn ev_abi_version() -> u32` — the
//! System V AMD64 ABI / AArch64 PCS places the value in the integer
//! return register (`rax` / `x0`), **never** in the float register.
//!
//! On Windows the same general-purpose register that holds the
//! integer happens to satisfy GMS's `ty_real` read path, which is why
//! Windows consumers see correct values today. On macOS arm64 the
//! float register is untouched and GMS reads zero (or whatever junk
//! was previously in `d0`), so every `u32` / `u64` / enum / `bool`
//! return shows up in GML as `0`. Affects the entire surface except
//! the six native `double`-returning fns and `ev_last_error`
//! (`ty_string`, which already reads the integer register).
//!
//! The shims here move the encoding out of the calling convention's
//! hands: each `<name>_gms` declares `-> f64`, so the value lands in
//! the float register on every platform. The encoding is a
//! `f64::from_bits()` of the original `as u64` cast — preserves the
//! bit pattern exactly, matching the convention the C smoke harness
//! in `examples/gms2-harness/main.c` already established for
//! pointer-as-double round-trips.
//!
//! ## What this does **not** affect
//!
//! Non-GMS consumers (Unity / C# / Godot / the C harness) keep
//! calling the original symbols. The shim symbols are purely
//! additive — no ABI bump required.
//!
//! See `examples/gms2-extension/extension/elevator_ffi/elevator_ffi_generated.gml`
//! (regenerated by `scripts/gen-gms-bindings.py`) for the GMS-side
//! `external_define` calls that target these shims.

#![allow(missing_docs)]
// Proper names (GameMaker, AArch64, AAPCS) in the module-level docs
// shouldn't need backticks — they're product/ABI names, not Rust idents.
#![allow(clippy::doc_markdown)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::cast_possible_wrap)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::ptr_as_ptr)]
// `use crate::*;` is intentional — every shim references a different
// item from the parent module, so an explicit import list would be
// ~130 names long for no expressive gain.
#![allow(clippy::wildcard_imports)]
// `ev_abi_version_gms` is the only shim whose underlying fn is
// `const`, but the macro emits one shape for every safe arm. Letting
// clippy pin the lint there forces a per-call-site annotation; the
// blanket allow keeps the macro uniform.
#![allow(clippy::missing_const_for_fn)]

use crate::*;
use std::ffi::c_char;

/// Defines a `<shim>` companion that forwards args to `<orig>` and
/// returns the result encoded as the bit pattern of an `f64`.
///
/// Both the shim and original identifier are passed in so the macro
/// works under the stable rules in Rust 1.88 (the `${concat(...)}`
/// metavar expression is still unstable as of 1.95). Each call site
/// pays for one repeated identifier; the suffix is always `_gms`.
///
/// Variants:
/// - `gms_shim!(unsafe <shim> = <orig>(args) -> Ret)` — for `unsafe extern "C"` originals
/// - `gms_shim!(<shim> = <orig>(args) -> Ret)` — for safe `extern "C"` originals
///   (rare; currently only `ev_abi_version`)
/// - `gms_shim!(i8 unsafe <shim> = <orig>(args))` — for `i8` returns; the result
///   is zero-extended through `u8` first so the bit pattern stays in the low
///   byte rather than sign-extending across the full mantissa
macro_rules! gms_shim {
    (unsafe $shim:ident = $orig:ident ( $($arg:ident: $argty:ty),* $(,)? ) -> $ret:ty) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $shim($($arg: $argty),*) -> f64 {
            let v: $ret = unsafe { $orig($($arg),*) };
            f64::from_bits(v as u64)
        }
    };
    ($shim:ident = $orig:ident ( $($arg:ident: $argty:ty),* $(,)? ) -> $ret:ty) => {
        #[unsafe(no_mangle)]
        pub extern "C" fn $shim($($arg: $argty),*) -> f64 {
            let v: $ret = $orig($($arg),*);
            f64::from_bits(v as u64)
        }
    };
    (i8 unsafe $shim:ident = $orig:ident ( $($arg:ident: $argty:ty),* $(,)? )) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $shim($($arg: $argty),*) -> f64 {
            let v: i8 = unsafe { $orig($($arg),*) };
            f64::from_bits(u64::from(v as u8))
        }
    };
}

// ── Generated shim invocations ────────────────────────────────────────────
//
// One per non-`double`/non-`void`/non-`char*`-returning `pub extern "C"`
// function. Sorted alphabetically to match the deterministic order
// of `scripts/gen-gms-bindings.py` so diffs stay tight when the FFI
// surface evolves. When adding or renaming an FFI function, add or
// rename the matching `gms_shim!()` line here.

gms_shim!(ev_abi_version_gms = ev_abi_version() -> u32);
gms_shim!(unsafe ev_drain_log_messages_gms = ev_drain_log_messages(handle: *mut EvSim, out: *mut EvLogMessage, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_pending_log_message_count_gms = ev_pending_log_message_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_abandoned_at_gms = ev_sim_abandoned_at(handle: *mut EvSim, stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_abandoned_count_at_gms = ev_sim_abandoned_count_at(handle: *mut EvSim, stop_entity_id: u64) -> u32);
gms_shim!(unsafe ev_sim_abort_movement_gms = ev_sim_abort_movement(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_add_elevator_gms = ev_sim_add_elevator(handle: *mut EvSim, params: *const EvElevatorParams, restricted_stops: *const u64, restricted_stops_count: u32, line_entity_id: u64, starting_position: f64, out_elevator_entity_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_add_group_gms = ev_sim_add_group(handle: *mut EvSim, name: *const c_char, strategy: EvStrategy, out_group_id: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_add_line_gms = ev_sim_add_line(handle: *mut EvSim, group_id: u32, name: *const c_char, min_position: f64, max_position: f64, max_cars: u32, out_line_entity_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_add_stop_gms = ev_sim_add_stop(handle: *mut EvSim, line_entity_id: u64, name: *const c_char, position: f64, out_stop_entity_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_add_stop_to_line_gms = ev_sim_add_stop_to_line(handle: *mut EvSim, stop_entity_id: u64, line_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_all_lines_gms = ev_sim_all_lines(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_all_tags_gms = ev_sim_all_tags(handle: *mut EvSim, out: *mut *mut c_char, capacity: u32, scratch: *mut c_char, scratch_capacity: u32, out_written: *mut u32, out_scratch_used: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_assign_line_to_group_gms = ev_sim_assign_line_to_group(handle: *mut EvSim, line_entity_id: u64, new_group: u32, out_old_group: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_assigned_car_gms = ev_sim_assigned_car(handle: *mut EvSim, stop_entity_id: u64, direction: i8, out_elevator: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_assigned_cars_by_line_gms = ev_sim_assigned_cars_by_line(handle: *mut EvSim, stop_entity_id: u64, direction: i8, out: *mut EvAssignment, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_best_eta_gms = ev_sim_best_eta(handle: *mut EvSim, stop_entity_id: u64, direction: i8, out_elevator: *mut u64, out_seconds: *mut f64) -> EvStatus);
gms_shim!(unsafe ev_sim_cancel_door_hold_gms = ev_sim_cancel_door_hold(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_car_call_count_gms = ev_sim_car_call_count(handle: *mut EvSim, elevator_entity_id: u64) -> u32);
gms_shim!(unsafe ev_sim_car_call_pending_riders_gms = ev_sim_car_call_pending_riders(handle: *mut EvSim, elevator_entity_id: u64, index: u32, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_car_calls_snapshot_gms = ev_sim_car_calls_snapshot(handle: *mut EvSim, elevator_entity_id: u64, out: *mut EvCarCall, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_clear_destinations_gms = ev_sim_clear_destinations(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_clear_elevator_home_stop_gms = ev_sim_clear_elevator_home_stop(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_close_door_gms = ev_sim_close_door(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_create_gms = ev_sim_create(config_path: *const c_char) -> *mut EvSim);
gms_shim!(unsafe ev_sim_current_tick_gms = ev_sim_current_tick(handle: *mut EvSim) -> u64);
gms_shim!(unsafe ev_sim_default_elevator_params_gms = ev_sim_default_elevator_params(out_params: *mut EvElevatorParams) -> EvStatus);
gms_shim!(unsafe ev_sim_despawn_rider_gms = ev_sim_despawn_rider(handle: *mut EvSim, rider_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_destination_queue_gms = ev_sim_destination_queue(handle: *mut EvSim, elevator_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_disable_gms = ev_sim_disable(handle: *mut EvSim, entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_drain_events_gms = ev_sim_drain_events(handle: *mut EvSim, out: *mut EvEvent, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(i8 unsafe ev_sim_elevator_direction_gms = ev_sim_elevator_direction(handle: *mut EvSim, elevator_entity_id: u64));
gms_shim!(unsafe ev_sim_elevator_entity_gms = ev_sim_elevator_entity(handle: *mut EvSim, elevator_config_id: u32) -> u64);
gms_shim!(unsafe ev_sim_elevator_going_down_gms = ev_sim_elevator_going_down(handle: *mut EvSim, elevator_entity_id: u64) -> bool);
gms_shim!(unsafe ev_sim_elevator_going_up_gms = ev_sim_elevator_going_up(handle: *mut EvSim, elevator_entity_id: u64) -> bool);
gms_shim!(unsafe ev_sim_elevator_home_stop_gms = ev_sim_elevator_home_stop(handle: *mut EvSim, elevator_entity_id: u64, out_stop_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_elevator_lookup_iter_gms = ev_sim_elevator_lookup_iter(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_elevator_move_count_gms = ev_sim_elevator_move_count(handle: *mut EvSim, elevator_entity_id: u64) -> u64);
gms_shim!(unsafe ev_sim_elevators_in_phase_gms = ev_sim_elevators_in_phase(handle: *mut EvSim, phase: u8, out_count: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_elevators_on_line_gms = ev_sim_elevators_on_line(handle: *mut EvSim, line_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_emergency_stop_gms = ev_sim_emergency_stop(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_enable_gms = ev_sim_enable(handle: *mut EvSim, entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_eta_gms = ev_sim_eta(handle: *mut EvSim, elevator_entity_id: u64, stop_entity_id: u64, out_ticks: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_eta_for_call_gms = ev_sim_eta_for_call(handle: *mut EvSim, stop_entity_id: u64, direction: i8, out_ticks: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_find_stop_at_position_on_line_gms = ev_sim_find_stop_at_position_on_line(handle: *mut EvSim, position: f64, line_entity_id: u64) -> u64);
gms_shim!(unsafe ev_sim_frame_gms = ev_sim_frame(handle: *mut EvSim, out: *mut EvFrame) -> EvStatus);
gms_shim!(unsafe ev_sim_groups_serving_stop_gms = ev_sim_groups_serving_stop(handle: *mut EvSim, stop_entity_id: u64, out: *mut u32, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_hall_call_count_gms = ev_sim_hall_call_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_hall_calls_snapshot_gms = ev_sim_hall_calls_snapshot(handle: *mut EvSim, out: *mut EvHallCall, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_hold_door_gms = ev_sim_hold_door(handle: *mut EvSim, elevator_entity_id: u64, ticks: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_idle_elevator_count_gms = ev_sim_idle_elevator_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_is_disabled_gms = ev_sim_is_disabled(handle: *mut EvSim, entity_id: u64) -> bool);
gms_shim!(unsafe ev_sim_is_elevator_gms = ev_sim_is_elevator(handle: *mut EvSim, entity_id: u64) -> bool);
#[cfg(feature = "loop_lines")]
gms_shim!(unsafe ev_sim_is_loop_gms = ev_sim_is_loop(handle: *mut EvSim, line_entity_id: u64) -> u8);
gms_shim!(unsafe ev_sim_is_rider_gms = ev_sim_is_rider(handle: *mut EvSim, entity_id: u64) -> bool);
gms_shim!(unsafe ev_sim_is_stop_gms = ev_sim_is_stop(handle: *mut EvSim, entity_id: u64) -> bool);
gms_shim!(unsafe ev_sim_iter_repositioning_elevators_gms = ev_sim_iter_repositioning_elevators(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_line_count_gms = ev_sim_line_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_line_entity_gms = ev_sim_line_entity(handle: *mut EvSim, line_config_id: u32) -> u64);
gms_shim!(unsafe ev_sim_line_for_elevator_gms = ev_sim_line_for_elevator(handle: *mut EvSim, elevator_entity_id: u64) -> u64);
gms_shim!(unsafe ev_sim_line_lookup_iter_gms = ev_sim_line_lookup_iter(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_lines_in_group_gms = ev_sim_lines_in_group(handle: *mut EvSim, group_id: u32, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_lines_serving_stop_gms = ev_sim_lines_serving_stop(handle: *mut EvSim, stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
#[cfg(feature = "loop_lines")]
gms_shim!(unsafe ev_sim_loop_circumference_gms = ev_sim_loop_circumference(handle: *mut EvSim, line_entity_id: u64, out_circumference: *mut f64) -> EvStatus);
#[cfg(feature = "loop_lines")]
gms_shim!(unsafe ev_sim_loop_forward_gap_gms = ev_sim_loop_forward_gap(handle: *mut EvSim, elevator_entity_id: u64, out_gap: *mut f64) -> EvStatus);
#[cfg(feature = "loop_lines")]
gms_shim!(unsafe ev_sim_loop_leader_gms = ev_sim_loop_leader(handle: *mut EvSim, elevator_entity_id: u64, out_leader: *mut u64) -> EvStatus);
#[cfg(feature = "loop_lines")]
gms_shim!(unsafe ev_sim_loop_next_stop_gms = ev_sim_loop_next_stop(handle: *mut EvSim, line_entity_id: u64, position: f64, out_stop: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_metrics_gms = ev_sim_metrics(handle: *mut EvSim, out_metrics: *mut EvMetrics) -> EvStatus);
gms_shim!(unsafe ev_sim_metrics_for_tag_gms = ev_sim_metrics_for_tag(handle: *mut EvSim, tag: *const c_char, out_metric: *mut EvTaggedMetric) -> EvStatus);
gms_shim!(unsafe ev_sim_occupancy_gms = ev_sim_occupancy(handle: *mut EvSim, elevator_entity_id: u64) -> u32);
gms_shim!(unsafe ev_sim_open_door_gms = ev_sim_open_door(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_pending_event_count_gms = ev_sim_pending_event_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_pin_assignment_gms = ev_sim_pin_assignment(handle: *mut EvSim, car_entity_id: u64, stop_entity_id: u64, direction: i8) -> EvStatus);
gms_shim!(unsafe ev_sim_press_car_button_gms = ev_sim_press_car_button(handle: *mut EvSim, car_entity_id: u64, floor_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_press_hall_button_gms = ev_sim_press_hall_button(handle: *mut EvSim, stop_entity_id: u64, direction: i8) -> EvStatus);
gms_shim!(unsafe ev_sim_push_destination_gms = ev_sim_push_destination(handle: *mut EvSim, elevator_entity_id: u64, stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_push_destination_front_gms = ev_sim_push_destination_front(handle: *mut EvSim, elevator_entity_id: u64, stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_reachable_stops_from_gms = ev_sim_reachable_stops_from(handle: *mut EvSim, from_stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_reassign_elevator_to_line_gms = ev_sim_reassign_elevator_to_line(handle: *mut EvSim, elevator_entity_id: u64, new_line_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_recall_to_gms = ev_sim_recall_to(handle: *mut EvSim, elevator_entity_id: u64, stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_remove_elevator_gms = ev_sim_remove_elevator(handle: *mut EvSim, elevator_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_remove_line_gms = ev_sim_remove_line(handle: *mut EvSim, line_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_remove_reposition_gms = ev_sim_remove_reposition(handle: *mut EvSim, group_id: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_remove_stop_gms = ev_sim_remove_stop(handle: *mut EvSim, stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_remove_stop_from_line_gms = ev_sim_remove_stop_from_line(handle: *mut EvSim, stop_entity_id: u64, line_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_reposition_id_gms = ev_sim_reposition_id(handle: *mut EvSim, group_id: u32, out_strategy: *mut EvReposition) -> EvStatus);
gms_shim!(unsafe ev_sim_reroute_gms = ev_sim_reroute(handle: *mut EvSim, rider_entity_id: u64, new_destination_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_reroute_rider_direct_gms = ev_sim_reroute_rider_direct(handle: *mut EvSim, rider_entity_id: u64, from_stop_entity_id: u64, to_stop_entity_id: u64, group_id: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_reroute_rider_shortest_gms = ev_sim_reroute_rider_shortest(handle: *mut EvSim, rider_entity_id: u64, to_stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_resident_count_at_gms = ev_sim_resident_count_at(handle: *mut EvSim, stop_entity_id: u64) -> u32);
gms_shim!(unsafe ev_sim_residents_at_gms = ev_sim_residents_at(handle: *mut EvSim, stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_rider_tag_gms = ev_sim_rider_tag(handle: *mut EvSim, rider_entity_id: u64, out_tag: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_riders_on_gms = ev_sim_riders_on(handle: *mut EvSim, elevator_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_run_until_quiet_gms = ev_sim_run_until_quiet(handle: *mut EvSim, max_ticks: u64, out_ticks_run: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_service_mode_gms = ev_sim_service_mode(handle: *mut EvSim, elevator_entity_id: u64, out_mode: *mut EvServiceMode) -> EvStatus);
gms_shim!(unsafe ev_sim_set_acceleration_gms = ev_sim_set_acceleration(handle: *mut EvSim, elevator_entity_id: u64, acceleration: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_arrival_log_retention_ticks_gms = ev_sim_set_arrival_log_retention_ticks(handle: *mut EvSim, retention_ticks: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_deceleration_gms = ev_sim_set_deceleration(handle: *mut EvSim, elevator_entity_id: u64, deceleration: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_door_open_ticks_gms = ev_sim_set_door_open_ticks(handle: *mut EvSim, elevator_entity_id: u64, ticks: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_set_door_transition_ticks_gms = ev_sim_set_door_transition_ticks(handle: *mut EvSim, elevator_entity_id: u64, ticks: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_set_elevator_home_stop_gms = ev_sim_set_elevator_home_stop(handle: *mut EvSim, elevator_entity_id: u64, home_stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_elevator_restricted_stops_gms = ev_sim_set_elevator_restricted_stops(handle: *mut EvSim, elevator_entity_id: u64, stop_ids: *const u64, count: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_set_line_range_gms = ev_sim_set_line_range(handle: *mut EvSim, line_entity_id: u64, min_position: f64, max_position: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_max_speed_gms = ev_sim_set_max_speed(handle: *mut EvSim, elevator_entity_id: u64, max_speed: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_reposition_gms = ev_sim_set_reposition(handle: *mut EvSim, group_id: u32, strategy: EvReposition) -> EvStatus);
gms_shim!(unsafe ev_sim_set_rider_access_gms = ev_sim_set_rider_access(handle: *mut EvSim, rider_entity_id: u64, stop_ids: *const u64, count: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_set_rider_route_direct_gms = ev_sim_set_rider_route_direct(handle: *mut EvSim, rider_entity_id: u64, from_stop_entity_id: u64, to_stop_entity_id: u64, group_id: u32) -> EvStatus);
gms_shim!(unsafe ev_sim_set_rider_route_shortest_gms = ev_sim_set_rider_route_shortest(handle: *mut EvSim, rider_entity_id: u64, to_stop_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_rider_tag_gms = ev_sim_set_rider_tag(handle: *mut EvSim, rider_entity_id: u64, tag: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_service_mode_gms = ev_sim_set_service_mode(handle: *mut EvSim, elevator_entity_id: u64, mode: EvServiceMode) -> EvStatus);
gms_shim!(unsafe ev_sim_set_strategy_gms = ev_sim_set_strategy(handle: *mut EvSim, group_id: u32, strategy: EvStrategy) -> EvStatus);
gms_shim!(unsafe ev_sim_set_target_velocity_gms = ev_sim_set_target_velocity(handle: *mut EvSim, elevator_entity_id: u64, velocity: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_set_weight_capacity_gms = ev_sim_set_weight_capacity(handle: *mut EvSim, elevator_entity_id: u64, capacity: f64) -> EvStatus);
gms_shim!(unsafe ev_sim_settle_rider_gms = ev_sim_settle_rider(handle: *mut EvSim, rider_entity_id: u64) -> EvStatus);
gms_shim!(unsafe ev_sim_shortest_route_gms = ev_sim_shortest_route(handle: *mut EvSim, from_stop_entity_id: u64, to_stop_entity_id: u64, out_stops: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_spawn_rider_gms = ev_sim_spawn_rider(handle: *mut EvSim, origin: u64, dest: u64, weight: f64, out_rider_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_spawn_rider_ex_gms = ev_sim_spawn_rider_ex(handle: *mut EvSim, origin: u64, dest: u64, weight: f64, skip_full_elevator: bool, max_crowding_factor: f64, abandon_after_ticks: i64, abandon_on_full: bool, max_wait_ticks: i64, out_rider_id: *mut u64) -> EvStatus);
gms_shim!(unsafe ev_sim_step_gms = ev_sim_step(handle: *mut EvSim) -> EvStatus);
gms_shim!(unsafe ev_sim_stop_entity_gms = ev_sim_stop_entity(handle: *mut EvSim, stop_id: u32) -> u64);
gms_shim!(unsafe ev_sim_stop_lookup_iter_gms = ev_sim_stop_lookup_iter(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_stops_served_by_line_gms = ev_sim_stops_served_by_line(handle: *mut EvSim, line_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_strategy_id_gms = ev_sim_strategy_id(handle: *mut EvSim, group_id: u32, out_strategy: *mut EvStrategy) -> EvStatus);
gms_shim!(unsafe ev_sim_tag_count_gms = ev_sim_tag_count(handle: *mut EvSim) -> u32);
gms_shim!(unsafe ev_sim_tag_entity_gms = ev_sim_tag_entity(handle: *mut EvSim, entity_id: u64, tag: *const c_char) -> EvStatus);
gms_shim!(unsafe ev_sim_transfer_points_gms = ev_sim_transfer_points(handle: *mut EvSim, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_unpin_assignment_gms = ev_sim_unpin_assignment(handle: *mut EvSim, stop_entity_id: u64, direction: i8) -> EvStatus);
gms_shim!(unsafe ev_sim_untag_entity_gms = ev_sim_untag_entity(handle: *mut EvSim, entity_id: u64, tag: *const c_char) -> EvStatus);
gms_shim!(unsafe ev_sim_waiting_at_gms = ev_sim_waiting_at(handle: *mut EvSim, stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_waiting_count_at_gms = ev_sim_waiting_count_at(handle: *mut EvSim, stop_entity_id: u64) -> u32);
gms_shim!(unsafe ev_sim_waiting_counts_by_line_at_gms = ev_sim_waiting_counts_by_line_at(handle: *mut EvSim, stop_entity_id: u64, out: *mut u64, capacity: u32, out_written: *mut u32) -> EvStatus);
gms_shim!(unsafe ev_sim_waiting_direction_counts_at_gms = ev_sim_waiting_direction_counts_at(handle: *mut EvSim, stop_entity_id: u64, out_up_count: *mut u32, out_down_count: *mut u32) -> EvStatus);

#[cfg(test)]
// `i8 → u8` cast in the i8 test is deliberate — it exercises the
// zero-extension hazard the shim guards against. Suppress the
// `needless_type_cast` nursery lint just inside the test module.
#[allow(clippy::needless_type_cast)]
mod tests {
    //! Sanity tests confirming the shim layer encodes each return shape
    //! correctly. The full GMS calling-convention round-trip can only be
    //! exercised by the GMS-shaped C harness in `examples/gms2-harness/`
    //! (and ultimately, a real GameMaker project); these tests just check
    //! that the bit-pattern encoding is invertible and matches the
    //! underlying API on the Rust side.

    use super::*;

    #[test]
    fn abi_version_shim_round_trips_to_original() {
        let original = ev_abi_version();
        let shimmed = ev_abi_version_gms();
        // Bit pattern of f64::from_bits(5_u64) is just 5 (a denormal).
        assert_eq!(shimmed.to_bits(), u64::from(original));
        // And it didn't accidentally become 5.0 (the value vs. bit-pattern check):
        // 5.0_f64 has bit pattern 0x4014_0000_0000_0000, very different from `5`.
        assert_ne!(shimmed.to_bits(), f64::from(original).to_bits());
    }

    #[test]
    fn bit_pattern_preserves_full_u64_range() {
        // Pointer-sized handles need the entire bit pattern intact —
        // confirm the encoding survives values outside the u32 / safe-int range.
        for v in [0_u64, 1, u32::MAX as u64, u64::MAX, 0xDEAD_BEEF_F00D_BABE] {
            let encoded = f64::from_bits(v);
            assert_eq!(encoded.to_bits(), v, "round-trip failed for {v:#x}");
        }
    }

    #[test]
    fn i8_shim_zero_extends_through_u8() {
        // Negative i8 must encode as 0xFF…0xFF in the low byte, NOT
        // sign-extended across the full mantissa — otherwise GML's
        // low-byte read would observe the wrong value. We declare the
        // value as i8 explicitly to make the sign-extension hazard
        // visible at the test site.
        // The `i8` annotation is deliberate: the shim's correctness
        // hinges on `i8 → u8` zero-extending the byte rather than sign-
        // extending. Declaring `raw_i8` as `u8` directly would erase the
        // hazard we're guarding against.
        let raw_i8: i8 = -1;
        let encoded = f64::from_bits(u64::from(raw_i8 as u8));
        assert_eq!(
            encoded.to_bits(),
            0xFF,
            "i8(-1) must encode as 0xFF, not 0xFFFFFFFFFFFFFFFF"
        );
    }
}
