/* AUTO-GENERATED by `cargo run -p elevator-layout-codegen`. DO NOT EDIT. */
/*
 * Source-of-truth: #[repr(C)] + #[derive(MultiHostLayout)] in
 * crates/elevator-ffi/src/lib.rs.
 *
 * Compile-time asserts pinning every field offset and total
 * struct size. A future cbindgen reorder breaks ffi-harness
 * here, before the GML decoders or C# bindings see
 * garbage values.
 */

#ifndef ELEVATOR_FFI_LAYOUT_ASSERTS_H
#define ELEVATOR_FFI_LAYOUT_ASSERTS_H

#include <stddef.h>
#include "elevator_ffi.h"

/* EvAssignment (16 bytes) */
_Static_assert(sizeof(struct EvAssignment) == 16, "EvAssignment size drift");
_Static_assert(offsetof(struct EvAssignment, line_entity_id) == 0, "EvAssignment.line_entity_id offset drift");
_Static_assert(offsetof(struct EvAssignment, car_entity_id) == 8, "EvAssignment.car_entity_id offset drift");

/* EvCarCall (40 bytes) */
_Static_assert(sizeof(struct EvCarCall) == 40, "EvCarCall size drift");
_Static_assert(offsetof(struct EvCarCall, car_entity_id) == 0, "EvCarCall.car_entity_id offset drift");
_Static_assert(offsetof(struct EvCarCall, floor_entity_id) == 8, "EvCarCall.floor_entity_id offset drift");
_Static_assert(offsetof(struct EvCarCall, press_tick) == 16, "EvCarCall.press_tick offset drift");
_Static_assert(offsetof(struct EvCarCall, acknowledged_at) == 24, "EvCarCall.acknowledged_at offset drift");
_Static_assert(offsetof(struct EvCarCall, ack_latency_ticks) == 32, "EvCarCall.ack_latency_ticks offset drift");
_Static_assert(offsetof(struct EvCarCall, pending_rider_count) == 36, "EvCarCall.pending_rider_count offset drift");

/* EvElevatorParams (64 bytes) */
_Static_assert(sizeof(struct EvElevatorParams) == 64, "EvElevatorParams size drift");
_Static_assert(offsetof(struct EvElevatorParams, max_speed) == 0, "EvElevatorParams.max_speed offset drift");
_Static_assert(offsetof(struct EvElevatorParams, acceleration) == 8, "EvElevatorParams.acceleration offset drift");
_Static_assert(offsetof(struct EvElevatorParams, deceleration) == 16, "EvElevatorParams.deceleration offset drift");
_Static_assert(offsetof(struct EvElevatorParams, weight_capacity) == 24, "EvElevatorParams.weight_capacity offset drift");
_Static_assert(offsetof(struct EvElevatorParams, door_transition_ticks) == 32, "EvElevatorParams.door_transition_ticks offset drift");
_Static_assert(offsetof(struct EvElevatorParams, door_open_ticks) == 36, "EvElevatorParams.door_open_ticks offset drift");
_Static_assert(offsetof(struct EvElevatorParams, inspection_speed_factor) == 40, "EvElevatorParams.inspection_speed_factor offset drift");
_Static_assert(offsetof(struct EvElevatorParams, bypass_load_up_pct) == 48, "EvElevatorParams.bypass_load_up_pct offset drift");
_Static_assert(offsetof(struct EvElevatorParams, bypass_load_down_pct) == 56, "EvElevatorParams.bypass_load_down_pct offset drift");

/* EvElevatorView (88 bytes) */
_Static_assert(sizeof(struct EvElevatorView) == 88, "EvElevatorView size drift");
_Static_assert(offsetof(struct EvElevatorView, entity_id) == 0, "EvElevatorView.entity_id offset drift");
_Static_assert(offsetof(struct EvElevatorView, group_id) == 8, "EvElevatorView.group_id offset drift");
_Static_assert(offsetof(struct EvElevatorView, line_id) == 16, "EvElevatorView.line_id offset drift");
_Static_assert(offsetof(struct EvElevatorView, phase) == 24, "EvElevatorView.phase offset drift");
_Static_assert(offsetof(struct EvElevatorView, position) == 32, "EvElevatorView.position offset drift");
_Static_assert(offsetof(struct EvElevatorView, velocity) == 40, "EvElevatorView.velocity offset drift");
_Static_assert(offsetof(struct EvElevatorView, current_stop_id) == 48, "EvElevatorView.current_stop_id offset drift");
_Static_assert(offsetof(struct EvElevatorView, target_stop_id) == 56, "EvElevatorView.target_stop_id offset drift");
_Static_assert(offsetof(struct EvElevatorView, occupancy) == 64, "EvElevatorView.occupancy offset drift");
_Static_assert(offsetof(struct EvElevatorView, capacity_kg) == 72, "EvElevatorView.capacity_kg offset drift");
_Static_assert(offsetof(struct EvElevatorView, door_state) == 80, "EvElevatorView.door_state offset drift");
_Static_assert(offsetof(struct EvElevatorView, going_up) == 81, "EvElevatorView.going_up offset drift");
_Static_assert(offsetof(struct EvElevatorView, going_down) == 82, "EvElevatorView.going_down offset drift");

/* EvEvent (88 bytes) */
_Static_assert(sizeof(struct EvEvent) == 88, "EvEvent size drift");
_Static_assert(offsetof(struct EvEvent, kind) == 0, "EvEvent.kind offset drift");
_Static_assert(offsetof(struct EvEvent, direction) == 1, "EvEvent.direction offset drift");
_Static_assert(offsetof(struct EvEvent, code1) == 2, "EvEvent.code1 offset drift");
_Static_assert(offsetof(struct EvEvent, code2) == 3, "EvEvent.code2 offset drift");
_Static_assert(offsetof(struct EvEvent, group) == 4, "EvEvent.group offset drift");
_Static_assert(offsetof(struct EvEvent, tick) == 8, "EvEvent.tick offset drift");
_Static_assert(offsetof(struct EvEvent, stop) == 16, "EvEvent.stop offset drift");
_Static_assert(offsetof(struct EvEvent, car) == 24, "EvEvent.car offset drift");
_Static_assert(offsetof(struct EvEvent, rider) == 32, "EvEvent.rider offset drift");
_Static_assert(offsetof(struct EvEvent, floor) == 40, "EvEvent.floor offset drift");
_Static_assert(offsetof(struct EvEvent, entity) == 48, "EvEvent.entity offset drift");
_Static_assert(offsetof(struct EvEvent, count) == 56, "EvEvent.count offset drift");
_Static_assert(offsetof(struct EvEvent, f1) == 64, "EvEvent.f1 offset drift");
_Static_assert(offsetof(struct EvEvent, f2) == 72, "EvEvent.f2 offset drift");
_Static_assert(offsetof(struct EvEvent, tag) == 80, "EvEvent.tag offset drift");

/* EvFrame (88 bytes) */
_Static_assert(sizeof(struct EvFrame) == 88, "EvFrame size drift");
_Static_assert(offsetof(struct EvFrame, elevators) == 0, "EvFrame.elevators offset drift");
_Static_assert(offsetof(struct EvFrame, elevator_count) == 8, "EvFrame.elevator_count offset drift");
_Static_assert(offsetof(struct EvFrame, stops) == 16, "EvFrame.stops offset drift");
_Static_assert(offsetof(struct EvFrame, stop_count) == 24, "EvFrame.stop_count offset drift");
_Static_assert(offsetof(struct EvFrame, riders) == 32, "EvFrame.riders offset drift");
_Static_assert(offsetof(struct EvFrame, rider_count) == 40, "EvFrame.rider_count offset drift");
_Static_assert(offsetof(struct EvFrame, metrics) == 48, "EvFrame.metrics offset drift");

/* EvHallCall (56 bytes) */
_Static_assert(sizeof(struct EvHallCall) == 56, "EvHallCall size drift");
_Static_assert(offsetof(struct EvHallCall, stop_entity_id) == 0, "EvHallCall.stop_entity_id offset drift");
_Static_assert(offsetof(struct EvHallCall, direction) == 8, "EvHallCall.direction offset drift");
_Static_assert(offsetof(struct EvHallCall, press_tick) == 16, "EvHallCall.press_tick offset drift");
_Static_assert(offsetof(struct EvHallCall, acknowledged_at) == 24, "EvHallCall.acknowledged_at offset drift");
_Static_assert(offsetof(struct EvHallCall, assigned_car) == 32, "EvHallCall.assigned_car offset drift");
_Static_assert(offsetof(struct EvHallCall, destination_entity_id) == 40, "EvHallCall.destination_entity_id offset drift");
_Static_assert(offsetof(struct EvHallCall, pinned) == 48, "EvHallCall.pinned offset drift");
_Static_assert(offsetof(struct EvHallCall, pending_rider_count) == 52, "EvHallCall.pending_rider_count offset drift");

/* EvLogMessage (32 bytes) */
_Static_assert(sizeof(struct EvLogMessage) == 32, "EvLogMessage size drift");
_Static_assert(offsetof(struct EvLogMessage, level) == 0, "EvLogMessage.level offset drift");
_Static_assert(offsetof(struct EvLogMessage, ts_ns) == 8, "EvLogMessage.ts_ns offset drift");
_Static_assert(offsetof(struct EvLogMessage, msg_ptr) == 16, "EvLogMessage.msg_ptr offset drift");
_Static_assert(offsetof(struct EvLogMessage, msg_len) == 24, "EvLogMessage.msg_len offset drift");

/* EvMetrics (112 bytes) */
_Static_assert(sizeof(struct EvMetrics) == 112, "EvMetrics size drift");
_Static_assert(offsetof(struct EvMetrics, total_delivered) == 0, "EvMetrics.total_delivered offset drift");
_Static_assert(offsetof(struct EvMetrics, total_abandoned) == 8, "EvMetrics.total_abandoned offset drift");
_Static_assert(offsetof(struct EvMetrics, total_spawned) == 16, "EvMetrics.total_spawned offset drift");
_Static_assert(offsetof(struct EvMetrics, total_settled) == 24, "EvMetrics.total_settled offset drift");
_Static_assert(offsetof(struct EvMetrics, total_rerouted) == 32, "EvMetrics.total_rerouted offset drift");
_Static_assert(offsetof(struct EvMetrics, throughput) == 40, "EvMetrics.throughput offset drift");
_Static_assert(offsetof(struct EvMetrics, avg_wait_ticks) == 48, "EvMetrics.avg_wait_ticks offset drift");
_Static_assert(offsetof(struct EvMetrics, max_wait_ticks) == 56, "EvMetrics.max_wait_ticks offset drift");
_Static_assert(offsetof(struct EvMetrics, avg_ride_ticks) == 64, "EvMetrics.avg_ride_ticks offset drift");
_Static_assert(offsetof(struct EvMetrics, avg_utilization) == 72, "EvMetrics.avg_utilization offset drift");
_Static_assert(offsetof(struct EvMetrics, abandonment_rate) == 80, "EvMetrics.abandonment_rate offset drift");
_Static_assert(offsetof(struct EvMetrics, total_distance) == 88, "EvMetrics.total_distance offset drift");
_Static_assert(offsetof(struct EvMetrics, total_moves) == 96, "EvMetrics.total_moves offset drift");
_Static_assert(offsetof(struct EvMetrics, reposition_distance) == 104, "EvMetrics.reposition_distance offset drift");

/* EvMetricsView (40 bytes) */
_Static_assert(sizeof(struct EvMetricsView) == 40, "EvMetricsView size drift");
_Static_assert(offsetof(struct EvMetricsView, total_delivered) == 0, "EvMetricsView.total_delivered offset drift");
_Static_assert(offsetof(struct EvMetricsView, total_abandoned) == 8, "EvMetricsView.total_abandoned offset drift");
_Static_assert(offsetof(struct EvMetricsView, avg_wait_seconds) == 16, "EvMetricsView.avg_wait_seconds offset drift");
_Static_assert(offsetof(struct EvMetricsView, avg_ride_seconds) == 24, "EvMetricsView.avg_ride_seconds offset drift");
_Static_assert(offsetof(struct EvMetricsView, current_tick) == 32, "EvMetricsView.current_tick offset drift");

/* EvRiderView (40 bytes) */
_Static_assert(sizeof(struct EvRiderView) == 40, "EvRiderView size drift");
_Static_assert(offsetof(struct EvRiderView, entity_id) == 0, "EvRiderView.entity_id offset drift");
_Static_assert(offsetof(struct EvRiderView, phase) == 8, "EvRiderView.phase offset drift");
_Static_assert(offsetof(struct EvRiderView, origin_stop_id) == 16, "EvRiderView.origin_stop_id offset drift");
_Static_assert(offsetof(struct EvRiderView, destination_stop_id) == 24, "EvRiderView.destination_stop_id offset drift");
_Static_assert(offsetof(struct EvRiderView, elevator_id) == 32, "EvRiderView.elevator_id offset drift");

/* EvStopView (56 bytes) */
_Static_assert(sizeof(struct EvStopView) == 56, "EvStopView size drift");
_Static_assert(offsetof(struct EvStopView, entity_id) == 0, "EvStopView.entity_id offset drift");
_Static_assert(offsetof(struct EvStopView, stop_id) == 8, "EvStopView.stop_id offset drift");
_Static_assert(offsetof(struct EvStopView, position) == 16, "EvStopView.position offset drift");
_Static_assert(offsetof(struct EvStopView, waiting) == 24, "EvStopView.waiting offset drift");
_Static_assert(offsetof(struct EvStopView, residents) == 28, "EvStopView.residents offset drift");
_Static_assert(offsetof(struct EvStopView, abandoned) == 32, "EvStopView.abandoned offset drift");
_Static_assert(offsetof(struct EvStopView, name_ptr) == 40, "EvStopView.name_ptr offset drift");
_Static_assert(offsetof(struct EvStopView, name_len) == 48, "EvStopView.name_len offset drift");

/* EvTaggedMetric (40 bytes) */
_Static_assert(sizeof(struct EvTaggedMetric) == 40, "EvTaggedMetric size drift");
_Static_assert(offsetof(struct EvTaggedMetric, avg_wait_ticks) == 0, "EvTaggedMetric.avg_wait_ticks offset drift");
_Static_assert(offsetof(struct EvTaggedMetric, max_wait_ticks) == 8, "EvTaggedMetric.max_wait_ticks offset drift");
_Static_assert(offsetof(struct EvTaggedMetric, total_delivered) == 16, "EvTaggedMetric.total_delivered offset drift");
_Static_assert(offsetof(struct EvTaggedMetric, total_abandoned) == 24, "EvTaggedMetric.total_abandoned offset drift");
_Static_assert(offsetof(struct EvTaggedMetric, total_spawned) == 32, "EvTaggedMetric.total_spawned offset drift");

#endif /* ELEVATOR_FFI_LAYOUT_ASSERTS_H */
