/* GameMaker-shaped C smoke harness for elevator-ffi.
 *
 * The csharp-harness already proves the cdylib loads and the ABI
 * round-trips through P/Invoke. This harness is stricter: it
 * exercises the FFI exactly the way GameMaker's `external_define`
 * would, where the only argument and return types are `ty_real`
 * (double) and `ty_string` (UTF-8 char*).
 *
 * What this catches that csharp-harness wouldn't:
 *   - Pointer-as-double round-trip (we cast handles through `double`
 *     before each call to confirm the bit pattern survives).
 *   - Struct field offsets in EvLogMessage match what
 *     extension/elevator_ffi/elevator_ffi.gml expects, so a future
 *     cbindgen reorder fails CI before the GML decoder breaks.
 *   - Lazy log polling activation behaves as documented (count call
 *     trips the flag; subsequent steps queue records).
 *
 * What this *doesn't* cover:
 *   - GameMaker's actual `external_define` dispatcher. We emulate the
 *     type constraints but not the runtime. A working extension still
 *     needs a manual GMS-side import per examples/gms2-extension/README.md.
 *
 * Build: examples/gms2-harness/build.sh resolves cc/cl per platform
 * and links against the in-tree libelevator_ffi shared object. CI runs
 * the same script as part of the ffi-harness matrix.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "elevator_ffi.h"

#define EXPECTED_ABI 5

/* ── GMS calling-convention bridge shims (issues #876 + #879) ────────
 * Forward-declared here because cbindgen does not expand the
 * `gms_shim!()` macro in crates/elevator-ffi/src/gms_shims.rs, so
 * these companion symbols aren't reflected in elevator_ffi.h.
 *
 * Each `_gms` shim's C signature is uniform: every non-`char*` slot
 * (args and return) rides `double`, matching GameMaker's
 * `ty_real`-only `external_call` transport. Pointer-typed args are
 * the address bit-pattern packed into an f64 via `f64::from_bits()`;
 * the shim unpacks via `f64::to_bits()` plus a cast back to the
 * native pointer type on its Rust side.
 *
 * Declaring the shims with native pointer arg types in C would put
 * the pointer in the integer register on x86_64 SysV / AAPCS,
 * while the Rust-side shim now reads from the float register — the
 * exact mismatch #879 reports. The single declaration below mirrors
 * the real Rust ABI, so calling these symbols from C looks
 * identical to how GameMaker calls them. */
extern double ev_abi_version_gms(void);
extern double ev_sim_step_gms(double handle_as_real);
extern double ev_sim_create_gms(const char *config_path);
extern double ev_sim_hall_call_count_gms(double handle_as_real);

/* ── Layout asserts ─────────────────────────────────────────────── */
/* layout_asserts.h is auto-generated by `cargo run -p
 * elevator-layout-codegen` from the #[repr(C)] +
 * #[derive(MultiHostLayout)] surface in
 * crates/elevator-ffi/src/lib.rs. CI's layout-drift-gate verifies
 * the committed file matches the regenerated output, so any cbindgen
 * reorder fails ffi-harness here before consumers see garbage. */
#include "layout_asserts.h"

_Static_assert(sizeof(void *) == 8, "elevator-ffi requires a 64-bit host");

/* ── Helpers ────────────────────────────────────────────────────── */

#define TICKS 600
#define LOG_BUF_CAPACITY 64

static int fail(const char *what) {
    const char *err = ev_last_error();
    fprintf(stderr, "FAIL: %s%s%s\n", what,
            err ? " — " : "", err ? err : "");
    return 1;
}

/* Round-trip a pointer through `double` storage. On x64 the user-space
 * address fits in 47 bits, well inside the 53-bit mantissa, so the
 * bit pattern survives losslessly. This is the same invariant
 * GameMaker relies on when `external_define` returns ty_real for a
 * pointer-returning C function. */
static void *real_to_handle(double r) {
    uint64_t u;
    memcpy(&u, &r, sizeof(u));
    return (void *)(uintptr_t)u;
}

static double handle_to_real(void *p) {
    uint64_t u = (uint64_t)(uintptr_t)p;
    double r;
    memcpy(&r, &u, sizeof(r));
    return r;
}

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s <path-to-config.ron>\n", argv[0]);
        return 2;
    }

    uint32_t abi = ev_abi_version();
    printf("ABI version: %u\n", abi);
    if (abi != EXPECTED_ABI) {
        fprintf(stderr, "ABI mismatch: harness expects %u, lib reports %u\n",
                EXPECTED_ABI, abi);
        return 1;
    }

    /* Stage the handle through `double` exactly the way GameMaker
     * would (external_define says ty_real for pointer args/returns).
     * If the bit pattern doesn't survive the round-trip, every
     * subsequent FFI call would dereference garbage. */
    struct EvSim *handle = ev_sim_create(argv[1]);
    if (!handle) {
        return fail("ev_sim_create");
    }
    double handle_as_real = handle_to_real(handle);
    struct EvSim *roundtrip = (struct EvSim *)real_to_handle(handle_as_real);
    if (roundtrip != handle) {
        fprintf(stderr, "FAIL: handle round-trip through double altered the pointer\n");
        ev_sim_destroy(handle);
        return 1;
    }

    /* Activate lazy log polling before the step loop. Mirrors the
     * pattern documented for GameMaker hosts in
     * extension/elevator_ffi/elevator_ffi.gml. */
    (void)ev_pending_log_message_count(roundtrip);

    for (int i = 0; i < TICKS; ++i) {
        if (ev_sim_step(roundtrip) != EvStatus_Ok) {
            ev_sim_destroy(roundtrip);
            return fail("ev_sim_step");
        }
    }

    /* Drain log messages; verify each EvLogMessage's borrowed slice
     * decodes as valid UTF-8 within msg_len. This mirrors what the
     * GML decoder in elevator_ffi.gml does on the GameMaker side. */
    struct EvLogMessage logs[LOG_BUF_CAPACITY];
    uint32_t written = 0;
    if (ev_drain_log_messages(roundtrip, logs, LOG_BUF_CAPACITY, &written) != EvStatus_Ok) {
        ev_sim_destroy(roundtrip);
        return fail("ev_drain_log_messages");
    }
    printf("drained log messages: %u\n", written);
    /* If the config emitted any events during the step loop, validate
     * the borrowed-slice round-trip. The default config is quiet so
     * `written == 0` is a legitimate outcome — the layout invariants
     * for that case are covered by the static asserts above and by
     * the "drain returns Ok with written = 0" path. */
    if (written > 0) {
        if (logs[0].msg_ptr == NULL || logs[0].msg_len == 0) {
            fprintf(stderr, "FAIL: first log record has null/empty borrowed slice\n");
            ev_sim_destroy(roundtrip);
            return 1;
        }
        /* Defensive bound — never trust a length-prefixed buffer
         * without a sanity cap. 1 MiB is generous for a
         * debug-formatted Event. */
        if (logs[0].msg_len > (1u << 20)) {
            fprintf(stderr, "FAIL: msg_len %u exceeds 1 MiB sanity cap\n", logs[0].msg_len);
            ev_sim_destroy(roundtrip);
            return 1;
        }
        printf("first log: level=%u ts_ns=%lld len=%u msg=\"%.*s\"\n",
               logs[0].level, (long long)logs[0].ts_ns, logs[0].msg_len,
               (int)logs[0].msg_len, (const char *)logs[0].msg_ptr);

        /* Confirm a second drain returns the same shape (now empty
         * since we just emptied it) without crashing on the cleared
         * log_drain_buf. */
        uint32_t second = 0;
        if (ev_drain_log_messages(roundtrip, logs, LOG_BUF_CAPACITY, &second) != EvStatus_Ok) {
            ev_sim_destroy(roundtrip);
            return fail("ev_drain_log_messages (second call)");
        }
        if (second != 0) {
            fprintf(stderr, "FAIL: second drain expected 0 records, got %u\n", second);
            ev_sim_destroy(roundtrip);
            return 1;
        }
    }

    /* ── GMS calling-convention bridge validation (issues #876 + #879) ─
     * Each `_gms` shim takes every non-string arg as `double` and
     * returns `double`, matching the only transport types GMS's
     * `external_call` understands. The shim Rust-side decodes the
     * inbound f64 bit pattern back to its native FFI type
     * (`*mut EvSim`, `u32`, `EvStatus`, …) and bit-encodes the
     * return the same way.
     *
     * Calling through the C declarations above produces the same
     * ABI shape on every platform — pointer args ride the float
     * register file (`xmm0..xmm7` / `d0..d7`) rather than the
     * integer register file. Pre-#877 the return register was
     * wrong; pre-#879 the arg registers were wrong. Both are now
     * covered end-to-end. */
    {
        double abi_real = ev_abi_version_gms();
        uint64_t abi_bits;
        memcpy(&abi_bits, &abi_real, sizeof(abi_bits));
        if ((uint32_t)abi_bits != EXPECTED_ABI) {
            fprintf(stderr,
                    "FAIL: ev_abi_version_gms bit pattern was %llu, expected %u\n",
                    (unsigned long long)abi_bits, EXPECTED_ABI);
            ev_sim_destroy(roundtrip);
            return 1;
        }

        double handle_as_real = handle_to_real(roundtrip);

        double step_real = ev_sim_step_gms(handle_as_real);
        uint64_t step_bits;
        memcpy(&step_bits, &step_real, sizeof(step_bits));
        if ((uint32_t)step_bits != (uint32_t)EvStatus_Ok) {
            fprintf(stderr,
                    "FAIL: ev_sim_step_gms returned %llu, expected EvStatus_Ok\n",
                    (unsigned long long)step_bits);
            ev_sim_destroy(roundtrip);
            return 1;
        }

        double count_real = ev_sim_hall_call_count_gms(handle_as_real);
        uint64_t count_bits;
        memcpy(&count_bits, &count_real, sizeof(count_bits));
        uint32_t count_direct = ev_sim_hall_call_count(roundtrip);
        if ((uint32_t)count_bits != count_direct) {
            fprintf(stderr,
                    "FAIL: ev_sim_hall_call_count_gms %llu disagrees with direct call %u\n",
                    (unsigned long long)count_bits, count_direct);
            ev_sim_destroy(roundtrip);
            return 1;
        }

        /* String arg keeps its native `const char *` type because
         * `ty_string` rides the integer register file on every ABI
         * — same convention C consumers use. */
        double create_real = ev_sim_create_gms(argv[1]);
        uint64_t create_bits;
        memcpy(&create_bits, &create_real, sizeof(create_bits));
        struct EvSim *gms_handle = (struct EvSim *)(uintptr_t)create_bits;
        if (gms_handle == NULL) {
            ev_sim_destroy(roundtrip);
            return fail("ev_sim_create_gms");
        }
        ev_sim_destroy(gms_handle);

        printf("GMS shim ABI bridge: abi=%u step=Ok hall_calls=%u\n",
               (uint32_t)abi_bits, count_direct);
    }

    ev_sim_destroy(roundtrip);
    printf("OK: GMS-shaped harness passed\n");
    return 0;
}
